// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.AttendanceStatus;
import com.school.base.domain.AttendanceStatusDataOnDemand;
import com.school.base.domain.AttendanceStatusIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AttendanceStatusIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AttendanceStatusIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AttendanceStatusIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AttendanceStatusIntegrationTest: @Transactional;
    
    @Autowired
    AttendanceStatusDataOnDemand AttendanceStatusIntegrationTest.dod;
    
    @Test
    public void AttendanceStatusIntegrationTest.testCountAttendanceStatuses() {
        Assert.assertNotNull("Data on demand for 'AttendanceStatus' failed to initialize correctly", dod.getRandomAttendanceStatus());
        long count = AttendanceStatus.countAttendanceStatuses();
        Assert.assertTrue("Counter for 'AttendanceStatus' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AttendanceStatusIntegrationTest.testFindAttendanceStatus() {
        AttendanceStatus obj = dod.getRandomAttendanceStatus();
        Assert.assertNotNull("Data on demand for 'AttendanceStatus' failed to initialize correctly", obj);
        Integer id = obj.getAttendanceStatusId();
        Assert.assertNotNull("Data on demand for 'AttendanceStatus' failed to provide an identifier", id);
        obj = AttendanceStatus.findAttendanceStatus(id);
        Assert.assertNotNull("Find method for 'AttendanceStatus' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AttendanceStatus' returned the incorrect identifier", id, obj.getAttendanceStatusId());
    }
    
    @Test
    public void AttendanceStatusIntegrationTest.testFindAllAttendanceStatuses() {
        Assert.assertNotNull("Data on demand for 'AttendanceStatus' failed to initialize correctly", dod.getRandomAttendanceStatus());
        long count = AttendanceStatus.countAttendanceStatuses();
        Assert.assertTrue("Too expensive to perform a find all test for 'AttendanceStatus', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AttendanceStatus> result = AttendanceStatus.findAllAttendanceStatuses();
        Assert.assertNotNull("Find all method for 'AttendanceStatus' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AttendanceStatus' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AttendanceStatusIntegrationTest.testFindAttendanceStatusEntries() {
        Assert.assertNotNull("Data on demand for 'AttendanceStatus' failed to initialize correctly", dod.getRandomAttendanceStatus());
        long count = AttendanceStatus.countAttendanceStatuses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AttendanceStatus> result = AttendanceStatus.findAttendanceStatusEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AttendanceStatus' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AttendanceStatus' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AttendanceStatusIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AttendanceStatus' failed to initialize correctly", dod.getRandomAttendanceStatus());
        AttendanceStatus obj = dod.getNewTransientAttendanceStatus(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AttendanceStatus' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AttendanceStatus' identifier to be null", obj.getAttendanceStatusId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'AttendanceStatus' identifier to no longer be null", obj.getAttendanceStatusId());
    }
    
    @Test
    public void AttendanceStatusIntegrationTest.testRemove() {
        AttendanceStatus obj = dod.getRandomAttendanceStatus();
        Assert.assertNotNull("Data on demand for 'AttendanceStatus' failed to initialize correctly", obj);
        Integer id = obj.getAttendanceStatusId();
        Assert.assertNotNull("Data on demand for 'AttendanceStatus' failed to provide an identifier", id);
        obj = AttendanceStatus.findAttendanceStatus(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AttendanceStatus' with identifier '" + id + "'", AttendanceStatus.findAttendanceStatus(id));
    }
    
}
