// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.BloodGroup;
import com.school.base.domain.BloodGroupDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect BloodGroupDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BloodGroupDataOnDemand: @Component;
    
    private Random BloodGroupDataOnDemand.rnd = new SecureRandom();
    
    private List<BloodGroup> BloodGroupDataOnDemand.data;
    
    public BloodGroup BloodGroupDataOnDemand.getNewTransientBloodGroup(int index) {
        BloodGroup obj = new BloodGroup();
        setBloodGroup(obj, index);
        return obj;
    }
    
    public void BloodGroupDataOnDemand.setBloodGroup(BloodGroup obj, int index) {
        String bloodGroup = "bloodGroup_" + index;
        if (bloodGroup.length() > 100) {
            bloodGroup = bloodGroup.substring(0, 100);
        }
        obj.setBloodGroup(bloodGroup);
    }
    
    public BloodGroup BloodGroupDataOnDemand.getSpecificBloodGroup(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        BloodGroup obj = data.get(index);
        Integer id = obj.getBloodGroupId();
        return BloodGroup.findBloodGroup(id);
    }
    
    public BloodGroup BloodGroupDataOnDemand.getRandomBloodGroup() {
        init();
        BloodGroup obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getBloodGroupId();
        return BloodGroup.findBloodGroup(id);
    }
    
    public boolean BloodGroupDataOnDemand.modifyBloodGroup(BloodGroup obj) {
        return false;
    }
    
    public void BloodGroupDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = BloodGroup.findBloodGroupEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'BloodGroup' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<BloodGroup>();
        for (int i = 0; i < 10; i++) {
            BloodGroup obj = getNewTransientBloodGroup(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
