// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.Caste;
import com.school.base.domain.CasteDataOnDemand;
import com.school.base.domain.CasteIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CasteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CasteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CasteIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CasteIntegrationTest: @Transactional;
    
    @Autowired
    CasteDataOnDemand CasteIntegrationTest.dod;
    
    @Test
    public void CasteIntegrationTest.testCountCastes() {
        Assert.assertNotNull("Data on demand for 'Caste' failed to initialize correctly", dod.getRandomCaste());
        long count = Caste.countCastes();
        Assert.assertTrue("Counter for 'Caste' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CasteIntegrationTest.testFindCaste() {
        Caste obj = dod.getRandomCaste();
        Assert.assertNotNull("Data on demand for 'Caste' failed to initialize correctly", obj);
        Integer id = obj.getCasteId();
        Assert.assertNotNull("Data on demand for 'Caste' failed to provide an identifier", id);
        obj = Caste.findCaste(id);
        Assert.assertNotNull("Find method for 'Caste' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Caste' returned the incorrect identifier", id, obj.getCasteId());
    }
    
    @Test
    public void CasteIntegrationTest.testFindAllCastes() {
        Assert.assertNotNull("Data on demand for 'Caste' failed to initialize correctly", dod.getRandomCaste());
        long count = Caste.countCastes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Caste', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Caste> result = Caste.findAllCastes();
        Assert.assertNotNull("Find all method for 'Caste' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Caste' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CasteIntegrationTest.testFindCasteEntries() {
        Assert.assertNotNull("Data on demand for 'Caste' failed to initialize correctly", dod.getRandomCaste());
        long count = Caste.countCastes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Caste> result = Caste.findCasteEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Caste' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Caste' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CasteIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Caste' failed to initialize correctly", dod.getRandomCaste());
        Caste obj = dod.getNewTransientCaste(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Caste' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Caste' identifier to be null", obj.getCasteId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Caste' identifier to no longer be null", obj.getCasteId());
    }
    
    @Test
    public void CasteIntegrationTest.testRemove() {
        Caste obj = dod.getRandomCaste();
        Assert.assertNotNull("Data on demand for 'Caste' failed to initialize correctly", obj);
        Integer id = obj.getCasteId();
        Assert.assertNotNull("Data on demand for 'Caste' failed to provide an identifier", id);
        obj = Caste.findCaste(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Caste' with identifier '" + id + "'", Caste.findCaste(id));
    }
    
}
