// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.Caste;
import com.school.base.domain.CasteDataOnDemand;
import com.school.base.domain.Religion;
import com.school.base.domain.ReligionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CasteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CasteDataOnDemand: @Component;
    
    private Random CasteDataOnDemand.rnd = new SecureRandom();
    
    private List<Caste> CasteDataOnDemand.data;
    
    @Autowired
    ReligionDataOnDemand CasteDataOnDemand.religionDataOnDemand;
    
    public Caste CasteDataOnDemand.getNewTransientCaste(int index) {
        Caste obj = new Caste();
        setCasteName(obj, index);
        setReligionId(obj, index);
        return obj;
    }
    
    public void CasteDataOnDemand.setCasteName(Caste obj, int index) {
        String casteName = "casteName_" + index;
        if (casteName.length() > 200) {
            casteName = casteName.substring(0, 200);
        }
        obj.setCasteName(casteName);
    }
    
    public void CasteDataOnDemand.setReligionId(Caste obj, int index) {
        Religion religionId = religionDataOnDemand.getRandomReligion();
        obj.setReligionId(religionId);
    }
    
    public Caste CasteDataOnDemand.getSpecificCaste(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Caste obj = data.get(index);
        Integer id = obj.getCasteId();
        return Caste.findCaste(id);
    }
    
    public Caste CasteDataOnDemand.getRandomCaste() {
        init();
        Caste obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getCasteId();
        return Caste.findCaste(id);
    }
    
    public boolean CasteDataOnDemand.modifyCaste(Caste obj) {
        return false;
    }
    
    public void CasteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Caste.findCasteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Caste' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Caste>();
        for (int i = 0; i < 10; i++) {
            Caste obj = getNewTransientCaste(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
