// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.City;
import com.school.base.domain.CityDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CityDataOnDemand: @Component;
    
    private Random CityDataOnDemand.rnd = new SecureRandom();
    
    private List<City> CityDataOnDemand.data;
    
    public City CityDataOnDemand.getNewTransientCity(int index) {
        City obj = new City();
        setCity(obj, index);
        return obj;
    }
    
    public void CityDataOnDemand.setCity(City obj, int index) {
        String city = "city_" + index;
        if (city.length() > 255) {
            city = city.substring(0, 255);
        }
        obj.setCity(city);
    }
    
    public City CityDataOnDemand.getSpecificCity(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        City obj = data.get(index);
        Integer id = obj.getCityId();
        return City.findCity(id);
    }
    
    public City CityDataOnDemand.getRandomCity() {
        init();
        City obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getCityId();
        return City.findCity(id);
    }
    
    public boolean CityDataOnDemand.modifyCity(City obj) {
        return false;
    }
    
    public void CityDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = City.findCityEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'City' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<City>();
        for (int i = 0; i < 10; i++) {
            City obj = getNewTransientCity(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
