// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.Examination;
import com.school.base.domain.ExaminationDataOnDemand;
import com.school.base.domain.ExaminationIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ExaminationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExaminationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ExaminationIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ExaminationIntegrationTest: @Transactional;
    
    @Autowired
    ExaminationDataOnDemand ExaminationIntegrationTest.dod;
    
    @Test
    public void ExaminationIntegrationTest.testCountExaminations() {
        Assert.assertNotNull("Data on demand for 'Examination' failed to initialize correctly", dod.getRandomExamination());
        long count = Examination.countExaminations();
        Assert.assertTrue("Counter for 'Examination' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ExaminationIntegrationTest.testFindExamination() {
        Examination obj = dod.getRandomExamination();
        Assert.assertNotNull("Data on demand for 'Examination' failed to initialize correctly", obj);
        Integer id = obj.getExaminationId();
        Assert.assertNotNull("Data on demand for 'Examination' failed to provide an identifier", id);
        obj = Examination.findExamination(id);
        Assert.assertNotNull("Find method for 'Examination' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Examination' returned the incorrect identifier", id, obj.getExaminationId());
    }
    
    @Test
    public void ExaminationIntegrationTest.testFindAllExaminations() {
        Assert.assertNotNull("Data on demand for 'Examination' failed to initialize correctly", dod.getRandomExamination());
        long count = Examination.countExaminations();
        Assert.assertTrue("Too expensive to perform a find all test for 'Examination', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Examination> result = Examination.findAllExaminations();
        Assert.assertNotNull("Find all method for 'Examination' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Examination' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ExaminationIntegrationTest.testFindExaminationEntries() {
        Assert.assertNotNull("Data on demand for 'Examination' failed to initialize correctly", dod.getRandomExamination());
        long count = Examination.countExaminations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Examination> result = Examination.findExaminationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Examination' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Examination' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ExaminationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Examination' failed to initialize correctly", dod.getRandomExamination());
        Examination obj = dod.getNewTransientExamination(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Examination' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Examination' identifier to be null", obj.getExaminationId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Examination' identifier to no longer be null", obj.getExaminationId());
    }
    
    @Test
    public void ExaminationIntegrationTest.testRemove() {
        Examination obj = dod.getRandomExamination();
        Assert.assertNotNull("Data on demand for 'Examination' failed to initialize correctly", obj);
        Integer id = obj.getExaminationId();
        Assert.assertNotNull("Data on demand for 'Examination' failed to provide an identifier", id);
        obj = Examination.findExamination(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Examination' with identifier '" + id + "'", Examination.findExamination(id));
    }
    
}
