// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.HolidayType;
import com.school.base.domain.HolidayTypeDataOnDemand;
import com.school.base.domain.HolidayTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HolidayTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HolidayTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HolidayTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HolidayTypeIntegrationTest: @Transactional;
    
    @Autowired
    HolidayTypeDataOnDemand HolidayTypeIntegrationTest.dod;
    
    @Test
    public void HolidayTypeIntegrationTest.testCountHolidayTypes() {
        Assert.assertNotNull("Data on demand for 'HolidayType' failed to initialize correctly", dod.getRandomHolidayType());
        long count = HolidayType.countHolidayTypes();
        Assert.assertTrue("Counter for 'HolidayType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HolidayTypeIntegrationTest.testFindHolidayType() {
        HolidayType obj = dod.getRandomHolidayType();
        Assert.assertNotNull("Data on demand for 'HolidayType' failed to initialize correctly", obj);
        Integer id = obj.getHolidayTypeId();
        Assert.assertNotNull("Data on demand for 'HolidayType' failed to provide an identifier", id);
        obj = HolidayType.findHolidayType(id);
        Assert.assertNotNull("Find method for 'HolidayType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HolidayType' returned the incorrect identifier", id, obj.getHolidayTypeId());
    }
    
    @Test
    public void HolidayTypeIntegrationTest.testFindAllHolidayTypes() {
        Assert.assertNotNull("Data on demand for 'HolidayType' failed to initialize correctly", dod.getRandomHolidayType());
        long count = HolidayType.countHolidayTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'HolidayType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HolidayType> result = HolidayType.findAllHolidayTypes();
        Assert.assertNotNull("Find all method for 'HolidayType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HolidayType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HolidayTypeIntegrationTest.testFindHolidayTypeEntries() {
        Assert.assertNotNull("Data on demand for 'HolidayType' failed to initialize correctly", dod.getRandomHolidayType());
        long count = HolidayType.countHolidayTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HolidayType> result = HolidayType.findHolidayTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HolidayType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HolidayType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HolidayTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HolidayType' failed to initialize correctly", dod.getRandomHolidayType());
        HolidayType obj = dod.getNewTransientHolidayType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HolidayType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HolidayType' identifier to be null", obj.getHolidayTypeId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'HolidayType' identifier to no longer be null", obj.getHolidayTypeId());
    }
    
    @Test
    public void HolidayTypeIntegrationTest.testRemove() {
        HolidayType obj = dod.getRandomHolidayType();
        Assert.assertNotNull("Data on demand for 'HolidayType' failed to initialize correctly", obj);
        Integer id = obj.getHolidayTypeId();
        Assert.assertNotNull("Data on demand for 'HolidayType' failed to provide an identifier", id);
        obj = HolidayType.findHolidayType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'HolidayType' with identifier '" + id + "'", HolidayType.findHolidayType(id));
    }
    
}
