// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.HolidayType;
import com.school.base.domain.HolidayTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect HolidayTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: HolidayTypeDataOnDemand: @Component;
    
    private Random HolidayTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<HolidayType> HolidayTypeDataOnDemand.data;
    
    public HolidayType HolidayTypeDataOnDemand.getNewTransientHolidayType(int index) {
        HolidayType obj = new HolidayType();
        setHolidayType(obj, index);
        return obj;
    }
    
    public void HolidayTypeDataOnDemand.setHolidayType(HolidayType obj, int index) {
        String holidayType = "holidayType_" + index;
        if (holidayType.length() > 255) {
            holidayType = holidayType.substring(0, 255);
        }
        obj.setHolidayType(holidayType);
    }
    
    public HolidayType HolidayTypeDataOnDemand.getSpecificHolidayType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        HolidayType obj = data.get(index);
        Integer id = obj.getHolidayTypeId();
        return HolidayType.findHolidayType(id);
    }
    
    public HolidayType HolidayTypeDataOnDemand.getRandomHolidayType() {
        init();
        HolidayType obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getHolidayTypeId();
        return HolidayType.findHolidayType(id);
    }
    
    public boolean HolidayTypeDataOnDemand.modifyHolidayType(HolidayType obj) {
        return false;
    }
    
    public void HolidayTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = HolidayType.findHolidayTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'HolidayType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<HolidayType>();
        for (int i = 0; i < 10; i++) {
            HolidayType obj = getNewTransientHolidayType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
