// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.HomeWorkType;
import com.school.base.domain.HomeWorkTypeDataOnDemand;
import com.school.base.domain.HomeWorkTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HomeWorkTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HomeWorkTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HomeWorkTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HomeWorkTypeIntegrationTest: @Transactional;
    
    @Autowired
    HomeWorkTypeDataOnDemand HomeWorkTypeIntegrationTest.dod;
    
    @Test
    public void HomeWorkTypeIntegrationTest.testCountHomeWorkTypes() {
        Assert.assertNotNull("Data on demand for 'HomeWorkType' failed to initialize correctly", dod.getRandomHomeWorkType());
        long count = HomeWorkType.countHomeWorkTypes();
        Assert.assertTrue("Counter for 'HomeWorkType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HomeWorkTypeIntegrationTest.testFindHomeWorkType() {
        HomeWorkType obj = dod.getRandomHomeWorkType();
        Assert.assertNotNull("Data on demand for 'HomeWorkType' failed to initialize correctly", obj);
        Integer id = obj.getHomeWorkTypeId();
        Assert.assertNotNull("Data on demand for 'HomeWorkType' failed to provide an identifier", id);
        obj = HomeWorkType.findHomeWorkType(id);
        Assert.assertNotNull("Find method for 'HomeWorkType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HomeWorkType' returned the incorrect identifier", id, obj.getHomeWorkTypeId());
    }
    
    @Test
    public void HomeWorkTypeIntegrationTest.testFindAllHomeWorkTypes() {
        Assert.assertNotNull("Data on demand for 'HomeWorkType' failed to initialize correctly", dod.getRandomHomeWorkType());
        long count = HomeWorkType.countHomeWorkTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'HomeWorkType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HomeWorkType> result = HomeWorkType.findAllHomeWorkTypes();
        Assert.assertNotNull("Find all method for 'HomeWorkType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HomeWorkType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HomeWorkTypeIntegrationTest.testFindHomeWorkTypeEntries() {
        Assert.assertNotNull("Data on demand for 'HomeWorkType' failed to initialize correctly", dod.getRandomHomeWorkType());
        long count = HomeWorkType.countHomeWorkTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HomeWorkType> result = HomeWorkType.findHomeWorkTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HomeWorkType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HomeWorkType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HomeWorkTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HomeWorkType' failed to initialize correctly", dod.getRandomHomeWorkType());
        HomeWorkType obj = dod.getNewTransientHomeWorkType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HomeWorkType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HomeWorkType' identifier to be null", obj.getHomeWorkTypeId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'HomeWorkType' identifier to no longer be null", obj.getHomeWorkTypeId());
    }
    
    @Test
    public void HomeWorkTypeIntegrationTest.testRemove() {
        HomeWorkType obj = dod.getRandomHomeWorkType();
        Assert.assertNotNull("Data on demand for 'HomeWorkType' failed to initialize correctly", obj);
        Integer id = obj.getHomeWorkTypeId();
        Assert.assertNotNull("Data on demand for 'HomeWorkType' failed to provide an identifier", id);
        obj = HomeWorkType.findHomeWorkType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'HomeWorkType' with identifier '" + id + "'", HomeWorkType.findHomeWorkType(id));
    }
    
}
