// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.Language;
import com.school.base.domain.LanguageDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect LanguageDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LanguageDataOnDemand: @Component;
    
    private Random LanguageDataOnDemand.rnd = new SecureRandom();
    
    private List<Language> LanguageDataOnDemand.data;
    
    public Language LanguageDataOnDemand.getNewTransientLanguage(int index) {
        Language obj = new Language();
        setLanguage(obj, index);
        return obj;
    }
    
    public void LanguageDataOnDemand.setLanguage(Language obj, int index) {
        String language = "language_" + index;
        if (language.length() > 255) {
            language = language.substring(0, 255);
        }
        obj.setLanguage(language);
    }
    
    public Language LanguageDataOnDemand.getSpecificLanguage(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Language obj = data.get(index);
        Integer id = obj.getLanguageId();
        return Language.findLanguage(id);
    }
    
    public Language LanguageDataOnDemand.getRandomLanguage() {
        init();
        Language obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getLanguageId();
        return Language.findLanguage(id);
    }
    
    public boolean LanguageDataOnDemand.modifyLanguage(Language obj) {
        return false;
    }
    
    public void LanguageDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Language.findLanguageEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Language' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Language>();
        for (int i = 0; i < 10; i++) {
            Language obj = getNewTransientLanguage(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
