// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.LeaveRegister;
import com.school.base.domain.LeaveRegisterDataOnDemand;
import com.school.base.domain.LeaveRegisterIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LeaveRegisterIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LeaveRegisterIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LeaveRegisterIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LeaveRegisterIntegrationTest: @Transactional;
    
    @Autowired
    LeaveRegisterDataOnDemand LeaveRegisterIntegrationTest.dod;
    
    @Test
    public void LeaveRegisterIntegrationTest.testCountLeaveRegisters() {
        Assert.assertNotNull("Data on demand for 'LeaveRegister' failed to initialize correctly", dod.getRandomLeaveRegister());
        long count = LeaveRegister.countLeaveRegisters();
        Assert.assertTrue("Counter for 'LeaveRegister' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LeaveRegisterIntegrationTest.testFindLeaveRegister() {
        LeaveRegister obj = dod.getRandomLeaveRegister();
        Assert.assertNotNull("Data on demand for 'LeaveRegister' failed to initialize correctly", obj);
        Integer id = obj.getLeaveRegisterId();
        Assert.assertNotNull("Data on demand for 'LeaveRegister' failed to provide an identifier", id);
        obj = LeaveRegister.findLeaveRegister(id);
        Assert.assertNotNull("Find method for 'LeaveRegister' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'LeaveRegister' returned the incorrect identifier", id, obj.getLeaveRegisterId());
    }
    
    @Test
    public void LeaveRegisterIntegrationTest.testFindAllLeaveRegisters() {
        Assert.assertNotNull("Data on demand for 'LeaveRegister' failed to initialize correctly", dod.getRandomLeaveRegister());
        long count = LeaveRegister.countLeaveRegisters();
        Assert.assertTrue("Too expensive to perform a find all test for 'LeaveRegister', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<LeaveRegister> result = LeaveRegister.findAllLeaveRegisters();
        Assert.assertNotNull("Find all method for 'LeaveRegister' illegally returned null", result);
        Assert.assertTrue("Find all method for 'LeaveRegister' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LeaveRegisterIntegrationTest.testFindLeaveRegisterEntries() {
        Assert.assertNotNull("Data on demand for 'LeaveRegister' failed to initialize correctly", dod.getRandomLeaveRegister());
        long count = LeaveRegister.countLeaveRegisters();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<LeaveRegister> result = LeaveRegister.findLeaveRegisterEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'LeaveRegister' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'LeaveRegister' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LeaveRegisterIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'LeaveRegister' failed to initialize correctly", dod.getRandomLeaveRegister());
        LeaveRegister obj = dod.getNewTransientLeaveRegister(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'LeaveRegister' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'LeaveRegister' identifier to be null", obj.getLeaveRegisterId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'LeaveRegister' identifier to no longer be null", obj.getLeaveRegisterId());
    }
    
    @Test
    public void LeaveRegisterIntegrationTest.testRemove() {
        LeaveRegister obj = dod.getRandomLeaveRegister();
        Assert.assertNotNull("Data on demand for 'LeaveRegister' failed to initialize correctly", obj);
        Integer id = obj.getLeaveRegisterId();
        Assert.assertNotNull("Data on demand for 'LeaveRegister' failed to provide an identifier", id);
        obj = LeaveRegister.findLeaveRegister(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'LeaveRegister' with identifier '" + id + "'", LeaveRegister.findLeaveRegister(id));
    }
    
}
