// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.LeaveStatus;
import com.school.base.domain.LeaveStatusDataOnDemand;
import com.school.base.domain.LeaveStatusIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LeaveStatusIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LeaveStatusIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LeaveStatusIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LeaveStatusIntegrationTest: @Transactional;
    
    @Autowired
    LeaveStatusDataOnDemand LeaveStatusIntegrationTest.dod;
    
    @Test
    public void LeaveStatusIntegrationTest.testCountLeaveStatuses() {
        Assert.assertNotNull("Data on demand for 'LeaveStatus' failed to initialize correctly", dod.getRandomLeaveStatus());
        long count = LeaveStatus.countLeaveStatuses();
        Assert.assertTrue("Counter for 'LeaveStatus' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LeaveStatusIntegrationTest.testFindLeaveStatus() {
        LeaveStatus obj = dod.getRandomLeaveStatus();
        Assert.assertNotNull("Data on demand for 'LeaveStatus' failed to initialize correctly", obj);
        Integer id = obj.getLeaveStatus();
        Assert.assertNotNull("Data on demand for 'LeaveStatus' failed to provide an identifier", id);
        obj = LeaveStatus.findLeaveStatus(id);
        Assert.assertNotNull("Find method for 'LeaveStatus' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'LeaveStatus' returned the incorrect identifier", id, obj.getLeaveStatus());
    }
    
    @Test
    public void LeaveStatusIntegrationTest.testFindAllLeaveStatuses() {
        Assert.assertNotNull("Data on demand for 'LeaveStatus' failed to initialize correctly", dod.getRandomLeaveStatus());
        long count = LeaveStatus.countLeaveStatuses();
        Assert.assertTrue("Too expensive to perform a find all test for 'LeaveStatus', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<LeaveStatus> result = LeaveStatus.findAllLeaveStatuses();
        Assert.assertNotNull("Find all method for 'LeaveStatus' illegally returned null", result);
        Assert.assertTrue("Find all method for 'LeaveStatus' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LeaveStatusIntegrationTest.testFindLeaveStatusEntries() {
        Assert.assertNotNull("Data on demand for 'LeaveStatus' failed to initialize correctly", dod.getRandomLeaveStatus());
        long count = LeaveStatus.countLeaveStatuses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<LeaveStatus> result = LeaveStatus.findLeaveStatusEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'LeaveStatus' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'LeaveStatus' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LeaveStatusIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'LeaveStatus' failed to initialize correctly", dod.getRandomLeaveStatus());
        LeaveStatus obj = dod.getNewTransientLeaveStatus(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'LeaveStatus' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'LeaveStatus' identifier to be null", obj.getLeaveStatus());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'LeaveStatus' identifier to no longer be null", obj.getLeaveStatus());
    }
    
    @Test
    public void LeaveStatusIntegrationTest.testRemove() {
        LeaveStatus obj = dod.getRandomLeaveStatus();
        Assert.assertNotNull("Data on demand for 'LeaveStatus' failed to initialize correctly", obj);
        Integer id = obj.getLeaveStatus();
        Assert.assertNotNull("Data on demand for 'LeaveStatus' failed to provide an identifier", id);
        obj = LeaveStatus.findLeaveStatus(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'LeaveStatus' with identifier '" + id + "'", LeaveStatus.findLeaveStatus(id));
    }
    
}
