// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.LeaveStatus;
import com.school.base.domain.LeaveStatusDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect LeaveStatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LeaveStatusDataOnDemand: @Component;
    
    private Random LeaveStatusDataOnDemand.rnd = new SecureRandom();
    
    private List<LeaveStatus> LeaveStatusDataOnDemand.data;
    
    public LeaveStatus LeaveStatusDataOnDemand.getNewTransientLeaveStatus(int index) {
        LeaveStatus obj = new LeaveStatus();
        setStatus(obj, index);
        return obj;
    }
    
    public void LeaveStatusDataOnDemand.setStatus(LeaveStatus obj, int index) {
        String status = "status_" + index;
        if (status.length() > 49) {
            status = status.substring(0, 49);
        }
        obj.setStatus(status);
    }
    
    public LeaveStatus LeaveStatusDataOnDemand.getSpecificLeaveStatus(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        LeaveStatus obj = data.get(index);
        Integer id = obj.getLeaveStatus();
        return LeaveStatus.findLeaveStatus(id);
    }
    
    public LeaveStatus LeaveStatusDataOnDemand.getRandomLeaveStatus() {
        init();
        LeaveStatus obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getLeaveStatus();
        return LeaveStatus.findLeaveStatus(id);
    }
    
    public boolean LeaveStatusDataOnDemand.modifyLeaveStatus(LeaveStatus obj) {
        return false;
    }
    
    public void LeaveStatusDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = LeaveStatus.findLeaveStatusEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'LeaveStatus' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<LeaveStatus>();
        for (int i = 0; i < 10; i++) {
            LeaveStatus obj = getNewTransientLeaveStatus(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
