// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.PaymentType;
import com.school.base.domain.PaymentTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PaymentTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PaymentTypeDataOnDemand: @Component;
    
    private Random PaymentTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<PaymentType> PaymentTypeDataOnDemand.data;
    
    public PaymentType PaymentTypeDataOnDemand.getNewTransientPaymentType(int index) {
        PaymentType obj = new PaymentType();
        setPaymentType(obj, index);
        return obj;
    }
    
    public void PaymentTypeDataOnDemand.setPaymentType(PaymentType obj, int index) {
        String paymentType = "paymentType_" + index;
        if (paymentType.length() > 255) {
            paymentType = paymentType.substring(0, 255);
        }
        obj.setPaymentType(paymentType);
    }
    
    public PaymentType PaymentTypeDataOnDemand.getSpecificPaymentType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PaymentType obj = data.get(index);
        Integer id = obj.getPaymentTypeId();
        return PaymentType.findPaymentType(id);
    }
    
    public PaymentType PaymentTypeDataOnDemand.getRandomPaymentType() {
        init();
        PaymentType obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getPaymentTypeId();
        return PaymentType.findPaymentType(id);
    }
    
    public boolean PaymentTypeDataOnDemand.modifyPaymentType(PaymentType obj) {
        return false;
    }
    
    public void PaymentTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PaymentType.findPaymentTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PaymentType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PaymentType>();
        for (int i = 0; i < 10; i++) {
            PaymentType obj = getNewTransientPaymentType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
