// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.PaymentType;
import com.school.base.domain.PaymentTypeDataOnDemand;
import com.school.base.domain.PaymentTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PaymentTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PaymentTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PaymentTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PaymentTypeIntegrationTest: @Transactional;
    
    @Autowired
    PaymentTypeDataOnDemand PaymentTypeIntegrationTest.dod;
    
    @Test
    public void PaymentTypeIntegrationTest.testCountPaymentTypes() {
        Assert.assertNotNull("Data on demand for 'PaymentType' failed to initialize correctly", dod.getRandomPaymentType());
        long count = PaymentType.countPaymentTypes();
        Assert.assertTrue("Counter for 'PaymentType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PaymentTypeIntegrationTest.testFindPaymentType() {
        PaymentType obj = dod.getRandomPaymentType();
        Assert.assertNotNull("Data on demand for 'PaymentType' failed to initialize correctly", obj);
        Integer id = obj.getPaymentTypeId();
        Assert.assertNotNull("Data on demand for 'PaymentType' failed to provide an identifier", id);
        obj = PaymentType.findPaymentType(id);
        Assert.assertNotNull("Find method for 'PaymentType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PaymentType' returned the incorrect identifier", id, obj.getPaymentTypeId());
    }
    
    @Test
    public void PaymentTypeIntegrationTest.testFindAllPaymentTypes() {
        Assert.assertNotNull("Data on demand for 'PaymentType' failed to initialize correctly", dod.getRandomPaymentType());
        long count = PaymentType.countPaymentTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'PaymentType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PaymentType> result = PaymentType.findAllPaymentTypes();
        Assert.assertNotNull("Find all method for 'PaymentType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PaymentType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PaymentTypeIntegrationTest.testFindPaymentTypeEntries() {
        Assert.assertNotNull("Data on demand for 'PaymentType' failed to initialize correctly", dod.getRandomPaymentType());
        long count = PaymentType.countPaymentTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PaymentType> result = PaymentType.findPaymentTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PaymentType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PaymentType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PaymentTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PaymentType' failed to initialize correctly", dod.getRandomPaymentType());
        PaymentType obj = dod.getNewTransientPaymentType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PaymentType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PaymentType' identifier to be null", obj.getPaymentTypeId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PaymentType' identifier to no longer be null", obj.getPaymentTypeId());
    }
    
    @Test
    public void PaymentTypeIntegrationTest.testRemove() {
        PaymentType obj = dod.getRandomPaymentType();
        Assert.assertNotNull("Data on demand for 'PaymentType' failed to initialize correctly", obj);
        Integer id = obj.getPaymentTypeId();
        Assert.assertNotNull("Data on demand for 'PaymentType' failed to provide an identifier", id);
        obj = PaymentType.findPaymentType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PaymentType' with identifier '" + id + "'", PaymentType.findPaymentType(id));
    }
    
}
