// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.Postion;
import com.school.base.domain.PostionDataOnDemand;
import com.school.base.domain.PostionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PostionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PostionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PostionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PostionIntegrationTest: @Transactional;
    
    @Autowired
    PostionDataOnDemand PostionIntegrationTest.dod;
    
    @Test
    public void PostionIntegrationTest.testCountPostions() {
        Assert.assertNotNull("Data on demand for 'Postion' failed to initialize correctly", dod.getRandomPostion());
        long count = Postion.countPostions();
        Assert.assertTrue("Counter for 'Postion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PostionIntegrationTest.testFindPostion() {
        Postion obj = dod.getRandomPostion();
        Assert.assertNotNull("Data on demand for 'Postion' failed to initialize correctly", obj);
        Integer id = obj.getPostionId();
        Assert.assertNotNull("Data on demand for 'Postion' failed to provide an identifier", id);
        obj = Postion.findPostion(id);
        Assert.assertNotNull("Find method for 'Postion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Postion' returned the incorrect identifier", id, obj.getPostionId());
    }
    
    @Test
    public void PostionIntegrationTest.testFindAllPostions() {
        Assert.assertNotNull("Data on demand for 'Postion' failed to initialize correctly", dod.getRandomPostion());
        long count = Postion.countPostions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Postion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Postion> result = Postion.findAllPostions();
        Assert.assertNotNull("Find all method for 'Postion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Postion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PostionIntegrationTest.testFindPostionEntries() {
        Assert.assertNotNull("Data on demand for 'Postion' failed to initialize correctly", dod.getRandomPostion());
        long count = Postion.countPostions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Postion> result = Postion.findPostionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Postion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Postion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PostionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Postion' failed to initialize correctly", dod.getRandomPostion());
        Postion obj = dod.getNewTransientPostion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Postion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Postion' identifier to be null", obj.getPostionId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Postion' identifier to no longer be null", obj.getPostionId());
    }
    
    @Test
    public void PostionIntegrationTest.testRemove() {
        Postion obj = dod.getRandomPostion();
        Assert.assertNotNull("Data on demand for 'Postion' failed to initialize correctly", obj);
        Integer id = obj.getPostionId();
        Assert.assertNotNull("Data on demand for 'Postion' failed to provide an identifier", id);
        obj = Postion.findPostion(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Postion' with identifier '" + id + "'", Postion.findPostion(id));
    }
    
}
