// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.Postion;
import com.school.base.domain.PostionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PostionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PostionDataOnDemand: @Component;
    
    private Random PostionDataOnDemand.rnd = new SecureRandom();
    
    private List<Postion> PostionDataOnDemand.data;
    
    public Postion PostionDataOnDemand.getNewTransientPostion(int index) {
        Postion obj = new Postion();
        setPosition(obj, index);
        return obj;
    }
    
    public void PostionDataOnDemand.setPosition(Postion obj, int index) {
        String position = "position_" + index;
        if (position.length() > 200) {
            position = position.substring(0, 200);
        }
        obj.setPosition(position);
    }
    
    public Postion PostionDataOnDemand.getSpecificPostion(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Postion obj = data.get(index);
        Integer id = obj.getPostionId();
        return Postion.findPostion(id);
    }
    
    public Postion PostionDataOnDemand.getRandomPostion() {
        init();
        Postion obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getPostionId();
        return Postion.findPostion(id);
    }
    
    public boolean PostionDataOnDemand.modifyPostion(Postion obj) {
        return false;
    }
    
    public void PostionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Postion.findPostionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Postion' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Postion>();
        for (int i = 0; i < 10; i++) {
            Postion obj = getNewTransientPostion(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
