// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.Priority;
import com.school.base.domain.PriorityDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PriorityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PriorityDataOnDemand: @Component;
    
    private Random PriorityDataOnDemand.rnd = new SecureRandom();
    
    private List<Priority> PriorityDataOnDemand.data;
    
    public Priority PriorityDataOnDemand.getNewTransientPriority(int index) {
        Priority obj = new Priority();
        setPriority(obj, index);
        return obj;
    }
    
    public void PriorityDataOnDemand.setPriority(Priority obj, int index) {
        String priority = "priority_" + index;
        if (priority.length() > 100) {
            priority = priority.substring(0, 100);
        }
        obj.setPriority(priority);
    }
    
    public Priority PriorityDataOnDemand.getSpecificPriority(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Priority obj = data.get(index);
        Integer id = obj.getPriorityId();
        return Priority.findPriority(id);
    }
    
    public Priority PriorityDataOnDemand.getRandomPriority() {
        init();
        Priority obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getPriorityId();
        return Priority.findPriority(id);
    }
    
    public boolean PriorityDataOnDemand.modifyPriority(Priority obj) {
        return false;
    }
    
    public void PriorityDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Priority.findPriorityEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Priority' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Priority>();
        for (int i = 0; i < 10; i++) {
            Priority obj = getNewTransientPriority(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
