// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.Priority;
import com.school.base.domain.PriorityDataOnDemand;
import com.school.base.domain.PriorityIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PriorityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PriorityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PriorityIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PriorityIntegrationTest: @Transactional;
    
    @Autowired
    PriorityDataOnDemand PriorityIntegrationTest.dod;
    
    @Test
    public void PriorityIntegrationTest.testCountPrioritys() {
        Assert.assertNotNull("Data on demand for 'Priority' failed to initialize correctly", dod.getRandomPriority());
        long count = Priority.countPrioritys();
        Assert.assertTrue("Counter for 'Priority' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PriorityIntegrationTest.testFindPriority() {
        Priority obj = dod.getRandomPriority();
        Assert.assertNotNull("Data on demand for 'Priority' failed to initialize correctly", obj);
        Integer id = obj.getPriorityId();
        Assert.assertNotNull("Data on demand for 'Priority' failed to provide an identifier", id);
        obj = Priority.findPriority(id);
        Assert.assertNotNull("Find method for 'Priority' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Priority' returned the incorrect identifier", id, obj.getPriorityId());
    }
    
    @Test
    public void PriorityIntegrationTest.testFindAllPrioritys() {
        Assert.assertNotNull("Data on demand for 'Priority' failed to initialize correctly", dod.getRandomPriority());
        long count = Priority.countPrioritys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Priority', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Priority> result = Priority.findAllPrioritys();
        Assert.assertNotNull("Find all method for 'Priority' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Priority' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PriorityIntegrationTest.testFindPriorityEntries() {
        Assert.assertNotNull("Data on demand for 'Priority' failed to initialize correctly", dod.getRandomPriority());
        long count = Priority.countPrioritys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Priority> result = Priority.findPriorityEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Priority' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Priority' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PriorityIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Priority' failed to initialize correctly", dod.getRandomPriority());
        Priority obj = dod.getNewTransientPriority(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Priority' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Priority' identifier to be null", obj.getPriorityId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Priority' identifier to no longer be null", obj.getPriorityId());
    }
    
    @Test
    public void PriorityIntegrationTest.testRemove() {
        Priority obj = dod.getRandomPriority();
        Assert.assertNotNull("Data on demand for 'Priority' failed to initialize correctly", obj);
        Integer id = obj.getPriorityId();
        Assert.assertNotNull("Data on demand for 'Priority' failed to provide an identifier", id);
        obj = Priority.findPriority(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Priority' with identifier '" + id + "'", Priority.findPriority(id));
    }
    
}
