// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.ReceiptSchoolFee;
import com.school.base.domain.ReceiptSchoolFeeDataOnDemand;
import com.school.base.domain.SchoolFee;
import com.school.base.domain.SchoolFeeDataOnDemand;
import com.school.base.domain.SchoolFeeReceipt;
import com.school.base.domain.SchoolFeeReceiptDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ReceiptSchoolFeeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReceiptSchoolFeeDataOnDemand: @Component;
    
    private Random ReceiptSchoolFeeDataOnDemand.rnd = new SecureRandom();
    
    private List<ReceiptSchoolFee> ReceiptSchoolFeeDataOnDemand.data;
    
    @Autowired
    SchoolFeeDataOnDemand ReceiptSchoolFeeDataOnDemand.schoolFeeDataOnDemand;
    
    @Autowired
    SchoolFeeReceiptDataOnDemand ReceiptSchoolFeeDataOnDemand.schoolFeeReceiptDataOnDemand;
    
    public ReceiptSchoolFee ReceiptSchoolFeeDataOnDemand.getNewTransientReceiptSchoolFee(int index) {
        ReceiptSchoolFee obj = new ReceiptSchoolFee();
        setPaidAmount(obj, index);
        setSchoolFeeId(obj, index);
        setSchoolFeeReceiptId(obj, index);
        return obj;
    }
    
    public void ReceiptSchoolFeeDataOnDemand.setPaidAmount(ReceiptSchoolFee obj, int index) {
        Integer paidAmount = new Integer(index);
        obj.setPaidAmount(paidAmount);
    }
    
    public void ReceiptSchoolFeeDataOnDemand.setSchoolFeeId(ReceiptSchoolFee obj, int index) {
        SchoolFee schoolFeeId = schoolFeeDataOnDemand.getRandomSchoolFee();
        obj.setSchoolFeeId(schoolFeeId);
    }
    
    public void ReceiptSchoolFeeDataOnDemand.setSchoolFeeReceiptId(ReceiptSchoolFee obj, int index) {
        SchoolFeeReceipt schoolFeeReceiptId = schoolFeeReceiptDataOnDemand.getRandomSchoolFeeReceipt();
        obj.setSchoolFeeReceiptId(schoolFeeReceiptId);
    }
    
    public ReceiptSchoolFee ReceiptSchoolFeeDataOnDemand.getSpecificReceiptSchoolFee(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ReceiptSchoolFee obj = data.get(index);
        Long id = obj.getReceiptSchoolFeeId();
        return ReceiptSchoolFee.findReceiptSchoolFee(id);
    }
    
    public ReceiptSchoolFee ReceiptSchoolFeeDataOnDemand.getRandomReceiptSchoolFee() {
        init();
        ReceiptSchoolFee obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getReceiptSchoolFeeId();
        return ReceiptSchoolFee.findReceiptSchoolFee(id);
    }
    
    public boolean ReceiptSchoolFeeDataOnDemand.modifyReceiptSchoolFee(ReceiptSchoolFee obj) {
        return false;
    }
    
    public void ReceiptSchoolFeeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ReceiptSchoolFee.findReceiptSchoolFeeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ReceiptSchoolFee' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ReceiptSchoolFee>();
        for (int i = 0; i < 10; i++) {
            ReceiptSchoolFee obj = getNewTransientReceiptSchoolFee(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
