// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.Religion;
import com.school.base.domain.ReligionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ReligionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReligionDataOnDemand: @Component;
    
    private Random ReligionDataOnDemand.rnd = new SecureRandom();
    
    private List<Religion> ReligionDataOnDemand.data;
    
    public Religion ReligionDataOnDemand.getNewTransientReligion(int index) {
        Religion obj = new Religion();
        setReligion(obj, index);
        return obj;
    }
    
    public void ReligionDataOnDemand.setReligion(Religion obj, int index) {
        String religion = "religion_" + index;
        if (religion.length() > 255) {
            religion = religion.substring(0, 255);
        }
        obj.setReligion(religion);
    }
    
    public Religion ReligionDataOnDemand.getSpecificReligion(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Religion obj = data.get(index);
        Integer id = obj.getReligionId();
        return Religion.findReligion(id);
    }
    
    public Religion ReligionDataOnDemand.getRandomReligion() {
        init();
        Religion obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getReligionId();
        return Religion.findReligion(id);
    }
    
    public boolean ReligionDataOnDemand.modifyReligion(Religion obj) {
        return false;
    }
    
    public void ReligionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Religion.findReligionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Religion' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Religion>();
        for (int i = 0; i < 10; i++) {
            Religion obj = getNewTransientReligion(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
