// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.ResultType;
import com.school.base.domain.ResultTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ResultTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ResultTypeDataOnDemand: @Component;
    
    private Random ResultTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<ResultType> ResultTypeDataOnDemand.data;
    
    public ResultType ResultTypeDataOnDemand.getNewTransientResultType(int index) {
        ResultType obj = new ResultType();
        setResultType(obj, index);
        return obj;
    }
    
    public void ResultTypeDataOnDemand.setResultType(ResultType obj, int index) {
        String resultType = "resultType_" + index;
        if (resultType.length() > 255) {
            resultType = resultType.substring(0, 255);
        }
        obj.setResultType(resultType);
    }
    
    public ResultType ResultTypeDataOnDemand.getSpecificResultType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ResultType obj = data.get(index);
        Integer id = obj.getResultTypeId();
        return ResultType.findResultType(id);
    }
    
    public ResultType ResultTypeDataOnDemand.getRandomResultType() {
        init();
        ResultType obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getResultTypeId();
        return ResultType.findResultType(id);
    }
    
    public boolean ResultTypeDataOnDemand.modifyResultType(ResultType obj) {
        return false;
    }
    
    public void ResultTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ResultType.findResultTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ResultType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ResultType>();
        for (int i = 0; i < 10; i++) {
            ResultType obj = getNewTransientResultType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
