// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SchoolHoliday;
import com.school.base.domain.SchoolHolidayDataOnDemand;
import com.school.base.domain.SchoolHolidayIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SchoolHolidayIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SchoolHolidayIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SchoolHolidayIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SchoolHolidayIntegrationTest: @Transactional;
    
    @Autowired
    SchoolHolidayDataOnDemand SchoolHolidayIntegrationTest.dod;
    
    @Test
    public void SchoolHolidayIntegrationTest.testCountSchoolHolidays() {
        Assert.assertNotNull("Data on demand for 'SchoolHoliday' failed to initialize correctly", dod.getRandomSchoolHoliday());
        long count = SchoolHoliday.countSchoolHolidays();
        Assert.assertTrue("Counter for 'SchoolHoliday' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SchoolHolidayIntegrationTest.testFindSchoolHoliday() {
        SchoolHoliday obj = dod.getRandomSchoolHoliday();
        Assert.assertNotNull("Data on demand for 'SchoolHoliday' failed to initialize correctly", obj);
        Integer id = obj.getSchoolHolidayId();
        Assert.assertNotNull("Data on demand for 'SchoolHoliday' failed to provide an identifier", id);
        obj = SchoolHoliday.findSchoolHoliday(id);
        Assert.assertNotNull("Find method for 'SchoolHoliday' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SchoolHoliday' returned the incorrect identifier", id, obj.getSchoolHolidayId());
    }
    
    @Test
    public void SchoolHolidayIntegrationTest.testFindAllSchoolHolidays() {
        Assert.assertNotNull("Data on demand for 'SchoolHoliday' failed to initialize correctly", dod.getRandomSchoolHoliday());
        long count = SchoolHoliday.countSchoolHolidays();
        Assert.assertTrue("Too expensive to perform a find all test for 'SchoolHoliday', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SchoolHoliday> result = SchoolHoliday.findAllSchoolHolidays();
        Assert.assertNotNull("Find all method for 'SchoolHoliday' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SchoolHoliday' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SchoolHolidayIntegrationTest.testFindSchoolHolidayEntries() {
        Assert.assertNotNull("Data on demand for 'SchoolHoliday' failed to initialize correctly", dod.getRandomSchoolHoliday());
        long count = SchoolHoliday.countSchoolHolidays();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SchoolHoliday> result = SchoolHoliday.findSchoolHolidayEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SchoolHoliday' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SchoolHoliday' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SchoolHolidayIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SchoolHoliday' failed to initialize correctly", dod.getRandomSchoolHoliday());
        SchoolHoliday obj = dod.getNewTransientSchoolHoliday(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SchoolHoliday' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SchoolHoliday' identifier to be null", obj.getSchoolHolidayId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SchoolHoliday' identifier to no longer be null", obj.getSchoolHolidayId());
    }
    
    @Test
    public void SchoolHolidayIntegrationTest.testRemove() {
        SchoolHoliday obj = dod.getRandomSchoolHoliday();
        Assert.assertNotNull("Data on demand for 'SchoolHoliday' failed to initialize correctly", obj);
        Integer id = obj.getSchoolHolidayId();
        Assert.assertNotNull("Data on demand for 'SchoolHoliday' failed to provide an identifier", id);
        obj = SchoolHoliday.findSchoolHoliday(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SchoolHoliday' with identifier '" + id + "'", SchoolHoliday.findSchoolHoliday(id));
    }
    
}
