// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.School;
import com.school.base.domain.SchoolDataOnDemand;
import com.school.base.domain.SchoolSmsTemplate;
import com.school.base.domain.SchoolSmsTemplateDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SchoolSmsTemplateDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SchoolSmsTemplateDataOnDemand: @Component;
    
    private Random SchoolSmsTemplateDataOnDemand.rnd = new SecureRandom();
    
    private List<SchoolSmsTemplate> SchoolSmsTemplateDataOnDemand.data;
    
    @Autowired
    SchoolDataOnDemand SchoolSmsTemplateDataOnDemand.schoolDataOnDemand;
    
    public SchoolSmsTemplate SchoolSmsTemplateDataOnDemand.getNewTransientSchoolSmsTemplate(int index) {
        SchoolSmsTemplate obj = new SchoolSmsTemplate();
        setFooter(obj, index);
        setHeader(obj, index);
        setSchoolId(obj, index);
        setSmsTemplateName(obj, index);
        return obj;
    }
    
    public void SchoolSmsTemplateDataOnDemand.setFooter(SchoolSmsTemplate obj, int index) {
        String footer = "footer_" + index;
        if (footer.length() > 100) {
            footer = footer.substring(0, 100);
        }
        obj.setFooter(footer);
    }
    
    public void SchoolSmsTemplateDataOnDemand.setHeader(SchoolSmsTemplate obj, int index) {
        String header = "header_" + index;
        if (header.length() > 100) {
            header = header.substring(0, 100);
        }
        obj.setHeader(header);
    }
    
    public void SchoolSmsTemplateDataOnDemand.setSchoolId(SchoolSmsTemplate obj, int index) {
        School schoolId = schoolDataOnDemand.getRandomSchool();
        obj.setSchoolId(schoolId);
    }
    
    public void SchoolSmsTemplateDataOnDemand.setSmsTemplateName(SchoolSmsTemplate obj, int index) {
        String smsTemplateName = "smsTemplateName_" + index;
        if (smsTemplateName.length() > 100) {
            smsTemplateName = smsTemplateName.substring(0, 100);
        }
        obj.setSmsTemplateName(smsTemplateName);
    }
    
    public SchoolSmsTemplate SchoolSmsTemplateDataOnDemand.getSpecificSchoolSmsTemplate(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SchoolSmsTemplate obj = data.get(index);
        Integer id = obj.getSchoolSmsTemplateId();
        return SchoolSmsTemplate.findSchoolSmsTemplate(id);
    }
    
    public SchoolSmsTemplate SchoolSmsTemplateDataOnDemand.getRandomSchoolSmsTemplate() {
        init();
        SchoolSmsTemplate obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getSchoolSmsTemplateId();
        return SchoolSmsTemplate.findSchoolSmsTemplate(id);
    }
    
    public boolean SchoolSmsTemplateDataOnDemand.modifySchoolSmsTemplate(SchoolSmsTemplate obj) {
        return false;
    }
    
    public void SchoolSmsTemplateDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SchoolSmsTemplate.findSchoolSmsTemplateEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SchoolSmsTemplate' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SchoolSmsTemplate>();
        for (int i = 0; i < 10; i++) {
            SchoolSmsTemplate obj = getNewTransientSchoolSmsTemplate(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
