// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SchoolGroup;
import com.school.base.domain.SchoolGroupDataOnDemand;
import com.school.base.domain.SchoolGroupIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SchoolGroupIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SchoolGroupIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SchoolGroupIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SchoolGroupIntegrationTest: @Transactional;
    
    @Autowired
    SchoolGroupDataOnDemand SchoolGroupIntegrationTest.dod;
    
    @Test
    public void SchoolGroupIntegrationTest.testCountSchoolGroups() {
        Assert.assertNotNull("Data on demand for 'SchoolGroup' failed to initialize correctly", dod.getRandomSchoolGroup());
        long count = SchoolGroup.countSchoolGroups();
        Assert.assertTrue("Counter for 'SchoolGroup' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SchoolGroupIntegrationTest.testFindSchoolGroup() {
        SchoolGroup obj = dod.getRandomSchoolGroup();
        Assert.assertNotNull("Data on demand for 'SchoolGroup' failed to initialize correctly", obj);
        Integer id = obj.getSchoolGroupId();
        Assert.assertNotNull("Data on demand for 'SchoolGroup' failed to provide an identifier", id);
        obj = SchoolGroup.findSchoolGroup(id);
        Assert.assertNotNull("Find method for 'SchoolGroup' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SchoolGroup' returned the incorrect identifier", id, obj.getSchoolGroupId());
    }
    
    @Test
    public void SchoolGroupIntegrationTest.testFindAllSchoolGroups() {
        Assert.assertNotNull("Data on demand for 'SchoolGroup' failed to initialize correctly", dod.getRandomSchoolGroup());
        long count = SchoolGroup.countSchoolGroups();
        Assert.assertTrue("Too expensive to perform a find all test for 'SchoolGroup', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SchoolGroup> result = SchoolGroup.findAllSchoolGroups();
        Assert.assertNotNull("Find all method for 'SchoolGroup' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SchoolGroup' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SchoolGroupIntegrationTest.testFindSchoolGroupEntries() {
        Assert.assertNotNull("Data on demand for 'SchoolGroup' failed to initialize correctly", dod.getRandomSchoolGroup());
        long count = SchoolGroup.countSchoolGroups();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SchoolGroup> result = SchoolGroup.findSchoolGroupEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SchoolGroup' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SchoolGroup' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SchoolGroupIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SchoolGroup' failed to initialize correctly", dod.getRandomSchoolGroup());
        SchoolGroup obj = dod.getNewTransientSchoolGroup(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SchoolGroup' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SchoolGroup' identifier to be null", obj.getSchoolGroupId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SchoolGroup' identifier to no longer be null", obj.getSchoolGroupId());
    }
    
    @Test
    public void SchoolGroupIntegrationTest.testRemove() {
        SchoolGroup obj = dod.getRandomSchoolGroup();
        Assert.assertNotNull("Data on demand for 'SchoolGroup' failed to initialize correctly", obj);
        Integer id = obj.getSchoolGroupId();
        Assert.assertNotNull("Data on demand for 'SchoolGroup' failed to provide an identifier", id);
        obj = SchoolGroup.findSchoolGroup(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SchoolGroup' with identifier '" + id + "'", SchoolGroup.findSchoolGroup(id));
    }
    
}
