// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SchoolClass;
import com.school.base.domain.SchoolClassDataOnDemand;
import com.school.base.domain.SchoolClassIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SchoolClassIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SchoolClassIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SchoolClassIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SchoolClassIntegrationTest: @Transactional;
    
    @Autowired
    SchoolClassDataOnDemand SchoolClassIntegrationTest.dod;
    
    @Test
    public void SchoolClassIntegrationTest.testCountSchoolClasses() {
        Assert.assertNotNull("Data on demand for 'SchoolClass' failed to initialize correctly", dod.getRandomSchoolClass());
        long count = SchoolClass.countSchoolClasses();
        Assert.assertTrue("Counter for 'SchoolClass' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SchoolClassIntegrationTest.testFindSchoolClass() {
        SchoolClass obj = dod.getRandomSchoolClass();
        Assert.assertNotNull("Data on demand for 'SchoolClass' failed to initialize correctly", obj);
        Integer id = obj.getSchoolClassId();
        Assert.assertNotNull("Data on demand for 'SchoolClass' failed to provide an identifier", id);
        obj = SchoolClass.findSchoolClass(id);
        Assert.assertNotNull("Find method for 'SchoolClass' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SchoolClass' returned the incorrect identifier", id, obj.getSchoolClassId());
    }
    
    @Test
    public void SchoolClassIntegrationTest.testFindAllSchoolClasses() {
        Assert.assertNotNull("Data on demand for 'SchoolClass' failed to initialize correctly", dod.getRandomSchoolClass());
        long count = SchoolClass.countSchoolClasses();
        Assert.assertTrue("Too expensive to perform a find all test for 'SchoolClass', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SchoolClass> result = SchoolClass.findAllSchoolClasses();
        Assert.assertNotNull("Find all method for 'SchoolClass' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SchoolClass' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SchoolClassIntegrationTest.testFindSchoolClassEntries() {
        Assert.assertNotNull("Data on demand for 'SchoolClass' failed to initialize correctly", dod.getRandomSchoolClass());
        long count = SchoolClass.countSchoolClasses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SchoolClass> result = SchoolClass.findSchoolClassEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SchoolClass' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SchoolClass' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SchoolClassIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SchoolClass' failed to initialize correctly", dod.getRandomSchoolClass());
        SchoolClass obj = dod.getNewTransientSchoolClass(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SchoolClass' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SchoolClass' identifier to be null", obj.getSchoolClassId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SchoolClass' identifier to no longer be null", obj.getSchoolClassId());
    }
    
    @Test
    public void SchoolClassIntegrationTest.testRemove() {
        SchoolClass obj = dod.getRandomSchoolClass();
        Assert.assertNotNull("Data on demand for 'SchoolClass' failed to initialize correctly", obj);
        Integer id = obj.getSchoolClassId();
        Assert.assertNotNull("Data on demand for 'SchoolClass' failed to provide an identifier", id);
        obj = SchoolClass.findSchoolClass(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SchoolClass' with identifier '" + id + "'", SchoolClass.findSchoolClass(id));
    }
    
}
