// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SchoolLogin;
import com.school.base.domain.SchoolLoginDataOnDemand;
import com.school.base.domain.SchoolLoginIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SchoolLoginIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SchoolLoginIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SchoolLoginIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SchoolLoginIntegrationTest: @Transactional;
    
    @Autowired
    SchoolLoginDataOnDemand SchoolLoginIntegrationTest.dod;
    
    @Test
    public void SchoolLoginIntegrationTest.testCountSchoolLogins() {
        Assert.assertNotNull("Data on demand for 'SchoolLogin' failed to initialize correctly", dod.getRandomSchoolLogin());
        long count = SchoolLogin.countSchoolLogins();
        Assert.assertTrue("Counter for 'SchoolLogin' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SchoolLoginIntegrationTest.testFindSchoolLogin() {
        SchoolLogin obj = dod.getRandomSchoolLogin();
        Assert.assertNotNull("Data on demand for 'SchoolLogin' failed to initialize correctly", obj);
        Integer id = obj.getSchoolLoginId();
        Assert.assertNotNull("Data on demand for 'SchoolLogin' failed to provide an identifier", id);
        obj = SchoolLogin.findSchoolLogin(id);
        Assert.assertNotNull("Find method for 'SchoolLogin' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SchoolLogin' returned the incorrect identifier", id, obj.getSchoolLoginId());
    }
    
    @Test
    public void SchoolLoginIntegrationTest.testFindAllSchoolLogins() {
        Assert.assertNotNull("Data on demand for 'SchoolLogin' failed to initialize correctly", dod.getRandomSchoolLogin());
        long count = SchoolLogin.countSchoolLogins();
        Assert.assertTrue("Too expensive to perform a find all test for 'SchoolLogin', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SchoolLogin> result = SchoolLogin.findAllSchoolLogins();
        Assert.assertNotNull("Find all method for 'SchoolLogin' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SchoolLogin' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SchoolLoginIntegrationTest.testFindSchoolLoginEntries() {
        Assert.assertNotNull("Data on demand for 'SchoolLogin' failed to initialize correctly", dod.getRandomSchoolLogin());
        long count = SchoolLogin.countSchoolLogins();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SchoolLogin> result = SchoolLogin.findSchoolLoginEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SchoolLogin' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SchoolLogin' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SchoolLoginIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SchoolLogin' failed to initialize correctly", dod.getRandomSchoolLogin());
        SchoolLogin obj = dod.getNewTransientSchoolLogin(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SchoolLogin' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SchoolLogin' identifier to be null", obj.getSchoolLoginId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SchoolLogin' identifier to no longer be null", obj.getSchoolLoginId());
    }
    
    @Test
    public void SchoolLoginIntegrationTest.testRemove() {
        SchoolLogin obj = dod.getRandomSchoolLogin();
        Assert.assertNotNull("Data on demand for 'SchoolLogin' failed to initialize correctly", obj);
        Integer id = obj.getSchoolLoginId();
        Assert.assertNotNull("Data on demand for 'SchoolLogin' failed to provide an identifier", id);
        obj = SchoolLogin.findSchoolLogin(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SchoolLogin' with identifier '" + id + "'", SchoolLogin.findSchoolLogin(id));
    }
    
}
