// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SchoolDeparment;
import com.school.base.domain.SchoolDeparmentDataOnDemand;
import com.school.base.domain.SchoolDeparmentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SchoolDeparmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SchoolDeparmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SchoolDeparmentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SchoolDeparmentIntegrationTest: @Transactional;
    
    @Autowired
    SchoolDeparmentDataOnDemand SchoolDeparmentIntegrationTest.dod;
    
    @Test
    public void SchoolDeparmentIntegrationTest.testCountSchoolDeparments() {
        Assert.assertNotNull("Data on demand for 'SchoolDeparment' failed to initialize correctly", dod.getRandomSchoolDeparment());
        long count = SchoolDeparment.countSchoolDeparments();
        Assert.assertTrue("Counter for 'SchoolDeparment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SchoolDeparmentIntegrationTest.testFindSchoolDeparment() {
        SchoolDeparment obj = dod.getRandomSchoolDeparment();
        Assert.assertNotNull("Data on demand for 'SchoolDeparment' failed to initialize correctly", obj);
        Integer id = obj.getSchoolDeparmentId();
        Assert.assertNotNull("Data on demand for 'SchoolDeparment' failed to provide an identifier", id);
        obj = SchoolDeparment.findSchoolDeparment(id);
        Assert.assertNotNull("Find method for 'SchoolDeparment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SchoolDeparment' returned the incorrect identifier", id, obj.getSchoolDeparmentId());
    }
    
    @Test
    public void SchoolDeparmentIntegrationTest.testFindAllSchoolDeparments() {
        Assert.assertNotNull("Data on demand for 'SchoolDeparment' failed to initialize correctly", dod.getRandomSchoolDeparment());
        long count = SchoolDeparment.countSchoolDeparments();
        Assert.assertTrue("Too expensive to perform a find all test for 'SchoolDeparment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SchoolDeparment> result = SchoolDeparment.findAllSchoolDeparments();
        Assert.assertNotNull("Find all method for 'SchoolDeparment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SchoolDeparment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SchoolDeparmentIntegrationTest.testFindSchoolDeparmentEntries() {
        Assert.assertNotNull("Data on demand for 'SchoolDeparment' failed to initialize correctly", dod.getRandomSchoolDeparment());
        long count = SchoolDeparment.countSchoolDeparments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SchoolDeparment> result = SchoolDeparment.findSchoolDeparmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SchoolDeparment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SchoolDeparment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SchoolDeparmentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SchoolDeparment' failed to initialize correctly", dod.getRandomSchoolDeparment());
        SchoolDeparment obj = dod.getNewTransientSchoolDeparment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SchoolDeparment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SchoolDeparment' identifier to be null", obj.getSchoolDeparmentId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SchoolDeparment' identifier to no longer be null", obj.getSchoolDeparmentId());
    }
    
    @Test
    public void SchoolDeparmentIntegrationTest.testRemove() {
        SchoolDeparment obj = dod.getRandomSchoolDeparment();
        Assert.assertNotNull("Data on demand for 'SchoolDeparment' failed to initialize correctly", obj);
        Integer id = obj.getSchoolDeparmentId();
        Assert.assertNotNull("Data on demand for 'SchoolDeparment' failed to provide an identifier", id);
        obj = SchoolDeparment.findSchoolDeparment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SchoolDeparment' with identifier '" + id + "'", SchoolDeparment.findSchoolDeparment(id));
    }
    
}
