// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SchoolSmsTemplate;
import com.school.base.domain.SchoolSmsTemplateDataOnDemand;
import com.school.base.domain.SchoolSmsTemplateIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SchoolSmsTemplateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SchoolSmsTemplateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SchoolSmsTemplateIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SchoolSmsTemplateIntegrationTest: @Transactional;
    
    @Autowired
    SchoolSmsTemplateDataOnDemand SchoolSmsTemplateIntegrationTest.dod;
    
    @Test
    public void SchoolSmsTemplateIntegrationTest.testCountSchoolSmsTemplates() {
        Assert.assertNotNull("Data on demand for 'SchoolSmsTemplate' failed to initialize correctly", dod.getRandomSchoolSmsTemplate());
        long count = SchoolSmsTemplate.countSchoolSmsTemplates();
        Assert.assertTrue("Counter for 'SchoolSmsTemplate' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SchoolSmsTemplateIntegrationTest.testFindSchoolSmsTemplate() {
        SchoolSmsTemplate obj = dod.getRandomSchoolSmsTemplate();
        Assert.assertNotNull("Data on demand for 'SchoolSmsTemplate' failed to initialize correctly", obj);
        Integer id = obj.getSchoolSmsTemplateId();
        Assert.assertNotNull("Data on demand for 'SchoolSmsTemplate' failed to provide an identifier", id);
        obj = SchoolSmsTemplate.findSchoolSmsTemplate(id);
        Assert.assertNotNull("Find method for 'SchoolSmsTemplate' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SchoolSmsTemplate' returned the incorrect identifier", id, obj.getSchoolSmsTemplateId());
    }
    
    @Test
    public void SchoolSmsTemplateIntegrationTest.testFindAllSchoolSmsTemplates() {
        Assert.assertNotNull("Data on demand for 'SchoolSmsTemplate' failed to initialize correctly", dod.getRandomSchoolSmsTemplate());
        long count = SchoolSmsTemplate.countSchoolSmsTemplates();
        Assert.assertTrue("Too expensive to perform a find all test for 'SchoolSmsTemplate', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SchoolSmsTemplate> result = SchoolSmsTemplate.findAllSchoolSmsTemplates();
        Assert.assertNotNull("Find all method for 'SchoolSmsTemplate' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SchoolSmsTemplate' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SchoolSmsTemplateIntegrationTest.testFindSchoolSmsTemplateEntries() {
        Assert.assertNotNull("Data on demand for 'SchoolSmsTemplate' failed to initialize correctly", dod.getRandomSchoolSmsTemplate());
        long count = SchoolSmsTemplate.countSchoolSmsTemplates();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SchoolSmsTemplate> result = SchoolSmsTemplate.findSchoolSmsTemplateEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SchoolSmsTemplate' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SchoolSmsTemplate' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SchoolSmsTemplateIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SchoolSmsTemplate' failed to initialize correctly", dod.getRandomSchoolSmsTemplate());
        SchoolSmsTemplate obj = dod.getNewTransientSchoolSmsTemplate(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SchoolSmsTemplate' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SchoolSmsTemplate' identifier to be null", obj.getSchoolSmsTemplateId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SchoolSmsTemplate' identifier to no longer be null", obj.getSchoolSmsTemplateId());
    }
    
    @Test
    public void SchoolSmsTemplateIntegrationTest.testRemove() {
        SchoolSmsTemplate obj = dod.getRandomSchoolSmsTemplate();
        Assert.assertNotNull("Data on demand for 'SchoolSmsTemplate' failed to initialize correctly", obj);
        Integer id = obj.getSchoolSmsTemplateId();
        Assert.assertNotNull("Data on demand for 'SchoolSmsTemplate' failed to provide an identifier", id);
        obj = SchoolSmsTemplate.findSchoolSmsTemplate(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SchoolSmsTemplate' with identifier '" + id + "'", SchoolSmsTemplate.findSchoolSmsTemplate(id));
    }
    
}
