// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SchoolFeeReceipt;
import com.school.base.domain.SchoolFeeReceiptDataOnDemand;
import com.school.base.domain.SchoolFeeReceiptIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SchoolFeeReceiptIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SchoolFeeReceiptIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SchoolFeeReceiptIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SchoolFeeReceiptIntegrationTest: @Transactional;
    
    @Autowired
    SchoolFeeReceiptDataOnDemand SchoolFeeReceiptIntegrationTest.dod;
    
    @Test
    public void SchoolFeeReceiptIntegrationTest.testCountSchoolFeeReceipts() {
        Assert.assertNotNull("Data on demand for 'SchoolFeeReceipt' failed to initialize correctly", dod.getRandomSchoolFeeReceipt());
        long count = SchoolFeeReceipt.countSchoolFeeReceipts();
        Assert.assertTrue("Counter for 'SchoolFeeReceipt' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SchoolFeeReceiptIntegrationTest.testFindSchoolFeeReceipt() {
        SchoolFeeReceipt obj = dod.getRandomSchoolFeeReceipt();
        Assert.assertNotNull("Data on demand for 'SchoolFeeReceipt' failed to initialize correctly", obj);
        Long id = obj.getSchoolFeeReceiptId();
        Assert.assertNotNull("Data on demand for 'SchoolFeeReceipt' failed to provide an identifier", id);
        obj = SchoolFeeReceipt.findSchoolFeeReceipt(id);
        Assert.assertNotNull("Find method for 'SchoolFeeReceipt' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SchoolFeeReceipt' returned the incorrect identifier", id, obj.getSchoolFeeReceiptId());
    }
    
    @Test
    public void SchoolFeeReceiptIntegrationTest.testFindAllSchoolFeeReceipts() {
        Assert.assertNotNull("Data on demand for 'SchoolFeeReceipt' failed to initialize correctly", dod.getRandomSchoolFeeReceipt());
        long count = SchoolFeeReceipt.countSchoolFeeReceipts();
        Assert.assertTrue("Too expensive to perform a find all test for 'SchoolFeeReceipt', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SchoolFeeReceipt> result = SchoolFeeReceipt.findAllSchoolFeeReceipts();
        Assert.assertNotNull("Find all method for 'SchoolFeeReceipt' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SchoolFeeReceipt' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SchoolFeeReceiptIntegrationTest.testFindSchoolFeeReceiptEntries() {
        Assert.assertNotNull("Data on demand for 'SchoolFeeReceipt' failed to initialize correctly", dod.getRandomSchoolFeeReceipt());
        long count = SchoolFeeReceipt.countSchoolFeeReceipts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SchoolFeeReceipt> result = SchoolFeeReceipt.findSchoolFeeReceiptEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SchoolFeeReceipt' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SchoolFeeReceipt' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SchoolFeeReceiptIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SchoolFeeReceipt' failed to initialize correctly", dod.getRandomSchoolFeeReceipt());
        SchoolFeeReceipt obj = dod.getNewTransientSchoolFeeReceipt(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SchoolFeeReceipt' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SchoolFeeReceipt' identifier to be null", obj.getSchoolFeeReceiptId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SchoolFeeReceipt' identifier to no longer be null", obj.getSchoolFeeReceiptId());
    }
    
    @Test
    public void SchoolFeeReceiptIntegrationTest.testRemove() {
        SchoolFeeReceipt obj = dod.getRandomSchoolFeeReceipt();
        Assert.assertNotNull("Data on demand for 'SchoolFeeReceipt' failed to initialize correctly", obj);
        Long id = obj.getSchoolFeeReceiptId();
        Assert.assertNotNull("Data on demand for 'SchoolFeeReceipt' failed to provide an identifier", id);
        obj = SchoolFeeReceipt.findSchoolFeeReceipt(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SchoolFeeReceipt' with identifier '" + id + "'", SchoolFeeReceipt.findSchoolFeeReceipt(id));
    }
    
}
