// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.School;
import com.school.base.domain.SchoolDataOnDemand;
import com.school.base.domain.SchoolFeeType;
import com.school.base.domain.SchoolFeeTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SchoolFeeTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SchoolFeeTypeDataOnDemand: @Component;
    
    private Random SchoolFeeTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<SchoolFeeType> SchoolFeeTypeDataOnDemand.data;
    
    @Autowired
    SchoolDataOnDemand SchoolFeeTypeDataOnDemand.schoolDataOnDemand;
    
    public SchoolFeeType SchoolFeeTypeDataOnDemand.getNewTransientSchoolFeeType(int index) {
        SchoolFeeType obj = new SchoolFeeType();
        setDefaultAmount(obj, index);
        setFeeType(obj, index);
        setIsConcessionType(obj, index);
        setSchoolId(obj, index);
        return obj;
    }
    
    public void SchoolFeeTypeDataOnDemand.setDefaultAmount(SchoolFeeType obj, int index) {
        Float defaultAmount = new Integer(index).floatValue();
        if (defaultAmount > 9.99999999999E11F) {
            defaultAmount = 9.99999999999E11F;
        }
        obj.setDefaultAmount(defaultAmount);
    }
    
    public void SchoolFeeTypeDataOnDemand.setFeeType(SchoolFeeType obj, int index) {
        String feeType = "feeType_" + index;
        if (feeType.length() > 255) {
            feeType = feeType.substring(0, 255);
        }
        obj.setFeeType(feeType);
    }
    
    public void SchoolFeeTypeDataOnDemand.setIsConcessionType(SchoolFeeType obj, int index) {
        Integer isConcessionType = new Integer(index);
        obj.setIsConcessionType(isConcessionType);
    }
    
    public void SchoolFeeTypeDataOnDemand.setSchoolId(SchoolFeeType obj, int index) {
        School schoolId = schoolDataOnDemand.getRandomSchool();
        obj.setSchoolId(schoolId);
    }
    
    public SchoolFeeType SchoolFeeTypeDataOnDemand.getSpecificSchoolFeeType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SchoolFeeType obj = data.get(index);
        Integer id = obj.getSchoolFeeTypeId();
        return SchoolFeeType.findSchoolFeeType(id);
    }
    
    public SchoolFeeType SchoolFeeTypeDataOnDemand.getRandomSchoolFeeType() {
        init();
        SchoolFeeType obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getSchoolFeeTypeId();
        return SchoolFeeType.findSchoolFeeType(id);
    }
    
    public boolean SchoolFeeTypeDataOnDemand.modifySchoolFeeType(SchoolFeeType obj) {
        return false;
    }
    
    public void SchoolFeeTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SchoolFeeType.findSchoolFeeTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SchoolFeeType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SchoolFeeType>();
        for (int i = 0; i < 10; i++) {
            SchoolFeeType obj = getNewTransientSchoolFeeType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
