// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SchoolClassSection;
import com.school.base.domain.SchoolClassSectionDataOnDemand;
import com.school.base.domain.SchoolClassSectionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SchoolClassSectionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SchoolClassSectionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SchoolClassSectionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SchoolClassSectionIntegrationTest: @Transactional;
    
    @Autowired
    SchoolClassSectionDataOnDemand SchoolClassSectionIntegrationTest.dod;
    
    @Test
    public void SchoolClassSectionIntegrationTest.testCountSchoolClassSections() {
        Assert.assertNotNull("Data on demand for 'SchoolClassSection' failed to initialize correctly", dod.getRandomSchoolClassSection());
        long count = SchoolClassSection.countSchoolClassSections();
        Assert.assertTrue("Counter for 'SchoolClassSection' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SchoolClassSectionIntegrationTest.testFindSchoolClassSection() {
        SchoolClassSection obj = dod.getRandomSchoolClassSection();
        Assert.assertNotNull("Data on demand for 'SchoolClassSection' failed to initialize correctly", obj);
        Integer id = obj.getSchoolClassSectionId();
        Assert.assertNotNull("Data on demand for 'SchoolClassSection' failed to provide an identifier", id);
        obj = SchoolClassSection.findSchoolClassSection(id);
        Assert.assertNotNull("Find method for 'SchoolClassSection' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SchoolClassSection' returned the incorrect identifier", id, obj.getSchoolClassSectionId());
    }
    
    @Test
    public void SchoolClassSectionIntegrationTest.testFindAllSchoolClassSections() {
        Assert.assertNotNull("Data on demand for 'SchoolClassSection' failed to initialize correctly", dod.getRandomSchoolClassSection());
        long count = SchoolClassSection.countSchoolClassSections();
        Assert.assertTrue("Too expensive to perform a find all test for 'SchoolClassSection', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SchoolClassSection> result = SchoolClassSection.findAllSchoolClassSections();
        Assert.assertNotNull("Find all method for 'SchoolClassSection' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SchoolClassSection' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SchoolClassSectionIntegrationTest.testFindSchoolClassSectionEntries() {
        Assert.assertNotNull("Data on demand for 'SchoolClassSection' failed to initialize correctly", dod.getRandomSchoolClassSection());
        long count = SchoolClassSection.countSchoolClassSections();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SchoolClassSection> result = SchoolClassSection.findSchoolClassSectionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SchoolClassSection' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SchoolClassSection' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SchoolClassSectionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SchoolClassSection' failed to initialize correctly", dod.getRandomSchoolClassSection());
        SchoolClassSection obj = dod.getNewTransientSchoolClassSection(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SchoolClassSection' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SchoolClassSection' identifier to be null", obj.getSchoolClassSectionId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SchoolClassSection' identifier to no longer be null", obj.getSchoolClassSectionId());
    }
    
    @Test
    public void SchoolClassSectionIntegrationTest.testRemove() {
        SchoolClassSection obj = dod.getRandomSchoolClassSection();
        Assert.assertNotNull("Data on demand for 'SchoolClassSection' failed to initialize correctly", obj);
        Integer id = obj.getSchoolClassSectionId();
        Assert.assertNotNull("Data on demand for 'SchoolClassSection' failed to provide an identifier", id);
        obj = SchoolClassSection.findSchoolClassSection(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SchoolClassSection' with identifier '" + id + "'", SchoolClassSection.findSchoolClassSection(id));
    }
    
}
