// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.School;
import com.school.base.domain.SchoolDataOnDemand;
import com.school.base.domain.SchoolSession;
import com.school.base.domain.SchoolSessionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SchoolSessionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SchoolSessionDataOnDemand: @Component;
    
    private Random SchoolSessionDataOnDemand.rnd = new SecureRandom();
    
    private List<SchoolSession> SchoolSessionDataOnDemand.data;
    
    @Autowired
    SchoolDataOnDemand SchoolSessionDataOnDemand.schoolDataOnDemand;
    
    public SchoolSession SchoolSessionDataOnDemand.getNewTransientSchoolSession(int index) {
        SchoolSession obj = new SchoolSession();
        setSchoolId(obj, index);
        setSessionName(obj, index);
        setSessionTimings(obj, index);
        return obj;
    }
    
    public void SchoolSessionDataOnDemand.setSchoolId(SchoolSession obj, int index) {
        School schoolId = schoolDataOnDemand.getRandomSchool();
        obj.setSchoolId(schoolId);
    }
    
    public void SchoolSessionDataOnDemand.setSessionName(SchoolSession obj, int index) {
        String sessionName = "sessionName_" + index;
        if (sessionName.length() > 255) {
            sessionName = sessionName.substring(0, 255);
        }
        obj.setSessionName(sessionName);
    }
    
    public void SchoolSessionDataOnDemand.setSessionTimings(SchoolSession obj, int index) {
        String sessionTimings = "sessionTimings_" + index;
        if (sessionTimings.length() > 255) {
            sessionTimings = sessionTimings.substring(0, 255);
        }
        obj.setSessionTimings(sessionTimings);
    }
    
    public SchoolSession SchoolSessionDataOnDemand.getSpecificSchoolSession(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SchoolSession obj = data.get(index);
        Integer id = obj.getSchoolSessionId();
        return SchoolSession.findSchoolSession(id);
    }
    
    public SchoolSession SchoolSessionDataOnDemand.getRandomSchoolSession() {
        init();
        SchoolSession obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getSchoolSessionId();
        return SchoolSession.findSchoolSession(id);
    }
    
    public boolean SchoolSessionDataOnDemand.modifySchoolSession(SchoolSession obj) {
        return false;
    }
    
    public void SchoolSessionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SchoolSession.findSchoolSessionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SchoolSession' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SchoolSession>();
        for (int i = 0; i < 10; i++) {
            SchoolSession obj = getNewTransientSchoolSession(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
