// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SchoolSession;
import com.school.base.domain.SchoolSessionDataOnDemand;
import com.school.base.domain.SchoolSessionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SchoolSessionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SchoolSessionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SchoolSessionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SchoolSessionIntegrationTest: @Transactional;
    
    @Autowired
    SchoolSessionDataOnDemand SchoolSessionIntegrationTest.dod;
    
    @Test
    public void SchoolSessionIntegrationTest.testCountSchoolSessions() {
        Assert.assertNotNull("Data on demand for 'SchoolSession' failed to initialize correctly", dod.getRandomSchoolSession());
        long count = SchoolSession.countSchoolSessions();
        Assert.assertTrue("Counter for 'SchoolSession' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SchoolSessionIntegrationTest.testFindSchoolSession() {
        SchoolSession obj = dod.getRandomSchoolSession();
        Assert.assertNotNull("Data on demand for 'SchoolSession' failed to initialize correctly", obj);
        Integer id = obj.getSchoolSessionId();
        Assert.assertNotNull("Data on demand for 'SchoolSession' failed to provide an identifier", id);
        obj = SchoolSession.findSchoolSession(id);
        Assert.assertNotNull("Find method for 'SchoolSession' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SchoolSession' returned the incorrect identifier", id, obj.getSchoolSessionId());
    }
    
    @Test
    public void SchoolSessionIntegrationTest.testFindAllSchoolSessions() {
        Assert.assertNotNull("Data on demand for 'SchoolSession' failed to initialize correctly", dod.getRandomSchoolSession());
        long count = SchoolSession.countSchoolSessions();
        Assert.assertTrue("Too expensive to perform a find all test for 'SchoolSession', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SchoolSession> result = SchoolSession.findAllSchoolSessions();
        Assert.assertNotNull("Find all method for 'SchoolSession' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SchoolSession' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SchoolSessionIntegrationTest.testFindSchoolSessionEntries() {
        Assert.assertNotNull("Data on demand for 'SchoolSession' failed to initialize correctly", dod.getRandomSchoolSession());
        long count = SchoolSession.countSchoolSessions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SchoolSession> result = SchoolSession.findSchoolSessionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SchoolSession' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SchoolSession' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SchoolSessionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SchoolSession' failed to initialize correctly", dod.getRandomSchoolSession());
        SchoolSession obj = dod.getNewTransientSchoolSession(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SchoolSession' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SchoolSession' identifier to be null", obj.getSchoolSessionId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SchoolSession' identifier to no longer be null", obj.getSchoolSessionId());
    }
    
    @Test
    public void SchoolSessionIntegrationTest.testRemove() {
        SchoolSession obj = dod.getRandomSchoolSession();
        Assert.assertNotNull("Data on demand for 'SchoolSession' failed to initialize correctly", obj);
        Integer id = obj.getSchoolSessionId();
        Assert.assertNotNull("Data on demand for 'SchoolSession' failed to provide an identifier", id);
        obj = SchoolSession.findSchoolSession(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SchoolSession' with identifier '" + id + "'", SchoolSession.findSchoolSession(id));
    }
    
}
