// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SchoolFeeType;
import com.school.base.domain.SchoolFeeTypeDataOnDemand;
import com.school.base.domain.SchoolFeeTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SchoolFeeTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SchoolFeeTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SchoolFeeTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SchoolFeeTypeIntegrationTest: @Transactional;
    
    @Autowired
    SchoolFeeTypeDataOnDemand SchoolFeeTypeIntegrationTest.dod;
    
    @Test
    public void SchoolFeeTypeIntegrationTest.testCountSchoolFeeTypes() {
        Assert.assertNotNull("Data on demand for 'SchoolFeeType' failed to initialize correctly", dod.getRandomSchoolFeeType());
        long count = SchoolFeeType.countSchoolFeeTypes();
        Assert.assertTrue("Counter for 'SchoolFeeType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SchoolFeeTypeIntegrationTest.testFindSchoolFeeType() {
        SchoolFeeType obj = dod.getRandomSchoolFeeType();
        Assert.assertNotNull("Data on demand for 'SchoolFeeType' failed to initialize correctly", obj);
        Integer id = obj.getSchoolFeeTypeId();
        Assert.assertNotNull("Data on demand for 'SchoolFeeType' failed to provide an identifier", id);
        obj = SchoolFeeType.findSchoolFeeType(id);
        Assert.assertNotNull("Find method for 'SchoolFeeType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SchoolFeeType' returned the incorrect identifier", id, obj.getSchoolFeeTypeId());
    }
    
    @Test
    public void SchoolFeeTypeIntegrationTest.testFindAllSchoolFeeTypes() {
        Assert.assertNotNull("Data on demand for 'SchoolFeeType' failed to initialize correctly", dod.getRandomSchoolFeeType());
        long count = SchoolFeeType.countSchoolFeeTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'SchoolFeeType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SchoolFeeType> result = SchoolFeeType.findAllSchoolFeeTypes();
        Assert.assertNotNull("Find all method for 'SchoolFeeType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SchoolFeeType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SchoolFeeTypeIntegrationTest.testFindSchoolFeeTypeEntries() {
        Assert.assertNotNull("Data on demand for 'SchoolFeeType' failed to initialize correctly", dod.getRandomSchoolFeeType());
        long count = SchoolFeeType.countSchoolFeeTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SchoolFeeType> result = SchoolFeeType.findSchoolFeeTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SchoolFeeType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SchoolFeeType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SchoolFeeTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SchoolFeeType' failed to initialize correctly", dod.getRandomSchoolFeeType());
        SchoolFeeType obj = dod.getNewTransientSchoolFeeType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SchoolFeeType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SchoolFeeType' identifier to be null", obj.getSchoolFeeTypeId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SchoolFeeType' identifier to no longer be null", obj.getSchoolFeeTypeId());
    }
    
    @Test
    public void SchoolFeeTypeIntegrationTest.testRemove() {
        SchoolFeeType obj = dod.getRandomSchoolFeeType();
        Assert.assertNotNull("Data on demand for 'SchoolFeeType' failed to initialize correctly", obj);
        Integer id = obj.getSchoolFeeTypeId();
        Assert.assertNotNull("Data on demand for 'SchoolFeeType' failed to provide an identifier", id);
        obj = SchoolFeeType.findSchoolFeeType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SchoolFeeType' with identifier '" + id + "'", SchoolFeeType.findSchoolFeeType(id));
    }
    
}
