// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.School;
import com.school.base.domain.SchoolDataOnDemand;
import com.school.base.domain.SchoolIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SchoolIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SchoolIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SchoolIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SchoolIntegrationTest: @Transactional;
    
    @Autowired
    SchoolDataOnDemand SchoolIntegrationTest.dod;
    
    @Test
    public void SchoolIntegrationTest.testCountSchools() {
        Assert.assertNotNull("Data on demand for 'School' failed to initialize correctly", dod.getRandomSchool());
        long count = School.countSchools();
        Assert.assertTrue("Counter for 'School' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SchoolIntegrationTest.testFindSchool() {
        School obj = dod.getRandomSchool();
        Assert.assertNotNull("Data on demand for 'School' failed to initialize correctly", obj);
        Integer id = obj.getSchoolId();
        Assert.assertNotNull("Data on demand for 'School' failed to provide an identifier", id);
        obj = School.findSchool(id);
        Assert.assertNotNull("Find method for 'School' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'School' returned the incorrect identifier", id, obj.getSchoolId());
    }
    
    @Test
    public void SchoolIntegrationTest.testFindAllSchools() {
        Assert.assertNotNull("Data on demand for 'School' failed to initialize correctly", dod.getRandomSchool());
        long count = School.countSchools();
        Assert.assertTrue("Too expensive to perform a find all test for 'School', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<School> result = School.findAllSchools();
        Assert.assertNotNull("Find all method for 'School' illegally returned null", result);
        Assert.assertTrue("Find all method for 'School' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SchoolIntegrationTest.testFindSchoolEntries() {
        Assert.assertNotNull("Data on demand for 'School' failed to initialize correctly", dod.getRandomSchool());
        long count = School.countSchools();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<School> result = School.findSchoolEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'School' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'School' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SchoolIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'School' failed to initialize correctly", dod.getRandomSchool());
        School obj = dod.getNewTransientSchool(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'School' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'School' identifier to be null", obj.getSchoolId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'School' identifier to no longer be null", obj.getSchoolId());
    }
    
    @Test
    public void SchoolIntegrationTest.testRemove() {
        School obj = dod.getRandomSchool();
        Assert.assertNotNull("Data on demand for 'School' failed to initialize correctly", obj);
        Integer id = obj.getSchoolId();
        Assert.assertNotNull("Data on demand for 'School' failed to provide an identifier", id);
        obj = School.findSchool(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'School' with identifier '" + id + "'", School.findSchool(id));
    }
    
}
