// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.HolidayTypeDataOnDemand;
import com.school.base.domain.School;
import com.school.base.domain.SchoolAcademicDataOnDemand;
import com.school.base.domain.SchoolDataOnDemand;
import com.school.base.domain.SchoolHoliday;
import com.school.base.domain.SchoolHolidayDataOnDemand;
import com.school.base.domain.Staff;
import com.school.base.domain.StaffDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SchoolHolidayDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SchoolHolidayDataOnDemand: @Component;
    
    private Random SchoolHolidayDataOnDemand.rnd = new SecureRandom();
    
    private List<SchoolHoliday> SchoolHolidayDataOnDemand.data;
    
    @Autowired
    StaffDataOnDemand SchoolHolidayDataOnDemand.staffDataOnDemand;
    
    @Autowired
    HolidayTypeDataOnDemand SchoolHolidayDataOnDemand.holidayTypeDataOnDemand;
    
    @Autowired
    SchoolAcademicDataOnDemand SchoolHolidayDataOnDemand.schoolAcademicDataOnDemand;
    
    @Autowired
    SchoolDataOnDemand SchoolHolidayDataOnDemand.schoolDataOnDemand;
    
    public SchoolHoliday SchoolHolidayDataOnDemand.getNewTransientSchoolHoliday(int index) {
        SchoolHoliday obj = new SchoolHoliday();
        setAuditCreatedDtTime(obj, index);
        setAuditModifiedDtTime(obj, index);
        setAuditUserId(obj, index);
        setHolidayDate(obj, index);
        setSchoolId(obj, index);
        return obj;
    }
    
    public void SchoolHolidayDataOnDemand.setAuditCreatedDtTime(SchoolHoliday obj, int index) {
        Calendar auditCreatedDtTime = Calendar.getInstance();
        obj.setAuditCreatedDtTime(auditCreatedDtTime);
    }
    
    public void SchoolHolidayDataOnDemand.setAuditModifiedDtTime(SchoolHoliday obj, int index) {
        Calendar auditModifiedDtTime = Calendar.getInstance();
        obj.setAuditModifiedDtTime(auditModifiedDtTime);
    }
    
    public void SchoolHolidayDataOnDemand.setAuditUserId(SchoolHoliday obj, int index) {
        Staff auditUserId = staffDataOnDemand.getRandomStaff();
        obj.setAuditUserId(auditUserId);
    }
    
    public void SchoolHolidayDataOnDemand.setHolidayDate(SchoolHoliday obj, int index) {
        Date holidayDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setHolidayDate(holidayDate);
    }
    
    public void SchoolHolidayDataOnDemand.setSchoolId(SchoolHoliday obj, int index) {
        School schoolId = schoolDataOnDemand.getRandomSchool();
        obj.setSchoolId(schoolId);
    }
    
    public SchoolHoliday SchoolHolidayDataOnDemand.getSpecificSchoolHoliday(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SchoolHoliday obj = data.get(index);
        Integer id = obj.getSchoolHolidayId();
        return SchoolHoliday.findSchoolHoliday(id);
    }
    
    public SchoolHoliday SchoolHolidayDataOnDemand.getRandomSchoolHoliday() {
        init();
        SchoolHoliday obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getSchoolHolidayId();
        return SchoolHoliday.findSchoolHoliday(id);
    }
    
    public boolean SchoolHolidayDataOnDemand.modifySchoolHoliday(SchoolHoliday obj) {
        return false;
    }
    
    public void SchoolHolidayDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SchoolHoliday.findSchoolHolidayEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SchoolHoliday' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SchoolHoliday>();
        for (int i = 0; i < 10; i++) {
            SchoolHoliday obj = getNewTransientSchoolHoliday(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
