// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.Section;
import com.school.base.domain.SectionDataOnDemand;
import com.school.base.domain.SectionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SectionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SectionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SectionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SectionIntegrationTest: @Transactional;
    
    @Autowired
    SectionDataOnDemand SectionIntegrationTest.dod;
    
    @Test
    public void SectionIntegrationTest.testCountSections() {
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", dod.getRandomSection());
        long count = Section.countSections();
        Assert.assertTrue("Counter for 'Section' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SectionIntegrationTest.testFindSection() {
        Section obj = dod.getRandomSection();
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", obj);
        Integer id = obj.getSectionId();
        Assert.assertNotNull("Data on demand for 'Section' failed to provide an identifier", id);
        obj = Section.findSection(id);
        Assert.assertNotNull("Find method for 'Section' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Section' returned the incorrect identifier", id, obj.getSectionId());
    }
    
    @Test
    public void SectionIntegrationTest.testFindAllSections() {
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", dod.getRandomSection());
        long count = Section.countSections();
        Assert.assertTrue("Too expensive to perform a find all test for 'Section', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Section> result = Section.findAllSections();
        Assert.assertNotNull("Find all method for 'Section' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Section' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SectionIntegrationTest.testFindSectionEntries() {
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", dod.getRandomSection());
        long count = Section.countSections();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Section> result = Section.findSectionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Section' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Section' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SectionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", dod.getRandomSection());
        Section obj = dod.getNewTransientSection(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Section' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Section' identifier to be null", obj.getSectionId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Section' identifier to no longer be null", obj.getSectionId());
    }
    
    @Test
    public void SectionIntegrationTest.testRemove() {
        Section obj = dod.getRandomSection();
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", obj);
        Integer id = obj.getSectionId();
        Assert.assertNotNull("Data on demand for 'Section' failed to provide an identifier", id);
        obj = Section.findSection(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Section' with identifier '" + id + "'", Section.findSection(id));
    }
    
}
