// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.Section;
import com.school.base.domain.SectionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SectionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SectionDataOnDemand: @Component;
    
    private Random SectionDataOnDemand.rnd = new SecureRandom();
    
    private List<Section> SectionDataOnDemand.data;
    
    public Section SectionDataOnDemand.getNewTransientSection(int index) {
        Section obj = new Section();
        setSection(obj, index);
        return obj;
    }
    
    public void SectionDataOnDemand.setSection(Section obj, int index) {
        String section = "section_" + index;
        if (section.length() > 10) {
            section = section.substring(0, 10);
        }
        obj.setSection(section);
    }
    
    public Section SectionDataOnDemand.getSpecificSection(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Section obj = data.get(index);
        Integer id = obj.getSectionId();
        return Section.findSection(id);
    }
    
    public Section SectionDataOnDemand.getRandomSection() {
        init();
        Section obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getSectionId();
        return Section.findSection(id);
    }
    
    public boolean SectionDataOnDemand.modifySection(Section obj) {
        return false;
    }
    
    public void SectionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Section.findSectionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Section' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Section>();
        for (int i = 0; i < 10; i++) {
            Section obj = getNewTransientSection(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
