// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.Sms;
import com.school.base.domain.SmsDataOnDemand;
import com.school.base.domain.SmsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SmsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SmsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SmsIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SmsIntegrationTest: @Transactional;
    
    @Autowired
    SmsDataOnDemand SmsIntegrationTest.dod;
    
    @Test
    public void SmsIntegrationTest.testCountSmses() {
        Assert.assertNotNull("Data on demand for 'Sms' failed to initialize correctly", dod.getRandomSms());
        long count = Sms.countSmses();
        Assert.assertTrue("Counter for 'Sms' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SmsIntegrationTest.testFindSms() {
        Sms obj = dod.getRandomSms();
        Assert.assertNotNull("Data on demand for 'Sms' failed to initialize correctly", obj);
        Long id = obj.getSmsId();
        Assert.assertNotNull("Data on demand for 'Sms' failed to provide an identifier", id);
        obj = Sms.findSms(id);
        Assert.assertNotNull("Find method for 'Sms' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Sms' returned the incorrect identifier", id, obj.getSmsId());
    }
    
    @Test
    public void SmsIntegrationTest.testFindAllSmses() {
        Assert.assertNotNull("Data on demand for 'Sms' failed to initialize correctly", dod.getRandomSms());
        long count = Sms.countSmses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Sms', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Sms> result = Sms.findAllSmses();
        Assert.assertNotNull("Find all method for 'Sms' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Sms' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SmsIntegrationTest.testFindSmsEntries() {
        Assert.assertNotNull("Data on demand for 'Sms' failed to initialize correctly", dod.getRandomSms());
        long count = Sms.countSmses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Sms> result = Sms.findSmsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Sms' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Sms' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SmsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Sms' failed to initialize correctly", dod.getRandomSms());
        Sms obj = dod.getNewTransientSms(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Sms' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Sms' identifier to be null", obj.getSmsId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Sms' identifier to no longer be null", obj.getSmsId());
    }
    
    @Test
    public void SmsIntegrationTest.testRemove() {
        Sms obj = dod.getRandomSms();
        Assert.assertNotNull("Data on demand for 'Sms' failed to initialize correctly", obj);
        Long id = obj.getSmsId();
        Assert.assertNotNull("Data on demand for 'Sms' failed to provide an identifier", id);
        obj = Sms.findSms(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Sms' with identifier '" + id + "'", Sms.findSms(id));
    }
    
}
