// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SmsStatus;
import com.school.base.domain.SmsStatusDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SmsStatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SmsStatusDataOnDemand: @Component;
    
    private Random SmsStatusDataOnDemand.rnd = new SecureRandom();
    
    private List<SmsStatus> SmsStatusDataOnDemand.data;
    
    public SmsStatus SmsStatusDataOnDemand.getNewTransientSmsStatus(int index) {
        SmsStatus obj = new SmsStatus();
        setSmsStatus(obj, index);
        return obj;
    }
    
    public void SmsStatusDataOnDemand.setSmsStatus(SmsStatus obj, int index) {
        String smsStatus = "smsStatus_" + index;
        if (smsStatus.length() > 100) {
            smsStatus = smsStatus.substring(0, 100);
        }
        obj.setSmsStatus(smsStatus);
    }
    
    public SmsStatus SmsStatusDataOnDemand.getSpecificSmsStatus(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SmsStatus obj = data.get(index);
        Integer id = obj.getSmsStatusId();
        return SmsStatus.findSmsStatus(id);
    }
    
    public SmsStatus SmsStatusDataOnDemand.getRandomSmsStatus() {
        init();
        SmsStatus obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getSmsStatusId();
        return SmsStatus.findSmsStatus(id);
    }
    
    public boolean SmsStatusDataOnDemand.modifySmsStatus(SmsStatus obj) {
        return false;
    }
    
    public void SmsStatusDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SmsStatus.findSmsStatusEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SmsStatus' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SmsStatus>();
        for (int i = 0; i < 10; i++) {
            SmsStatus obj = getNewTransientSmsStatus(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
