// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.StaffAttendance;
import com.school.base.domain.StaffAttendanceDataOnDemand;
import com.school.base.domain.StaffAttendanceIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StaffAttendanceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StaffAttendanceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StaffAttendanceIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StaffAttendanceIntegrationTest: @Transactional;
    
    @Autowired
    StaffAttendanceDataOnDemand StaffAttendanceIntegrationTest.dod;
    
    @Test
    public void StaffAttendanceIntegrationTest.testCountStaffAttendances() {
        Assert.assertNotNull("Data on demand for 'StaffAttendance' failed to initialize correctly", dod.getRandomStaffAttendance());
        long count = StaffAttendance.countStaffAttendances();
        Assert.assertTrue("Counter for 'StaffAttendance' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StaffAttendanceIntegrationTest.testFindStaffAttendance() {
        StaffAttendance obj = dod.getRandomStaffAttendance();
        Assert.assertNotNull("Data on demand for 'StaffAttendance' failed to initialize correctly", obj);
        Integer id = obj.getStaffAttendanceId();
        Assert.assertNotNull("Data on demand for 'StaffAttendance' failed to provide an identifier", id);
        obj = StaffAttendance.findStaffAttendance(id);
        Assert.assertNotNull("Find method for 'StaffAttendance' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StaffAttendance' returned the incorrect identifier", id, obj.getStaffAttendanceId());
    }
    
    @Test
    public void StaffAttendanceIntegrationTest.testFindAllStaffAttendances() {
        Assert.assertNotNull("Data on demand for 'StaffAttendance' failed to initialize correctly", dod.getRandomStaffAttendance());
        long count = StaffAttendance.countStaffAttendances();
        Assert.assertTrue("Too expensive to perform a find all test for 'StaffAttendance', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StaffAttendance> result = StaffAttendance.findAllStaffAttendances();
        Assert.assertNotNull("Find all method for 'StaffAttendance' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StaffAttendance' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StaffAttendanceIntegrationTest.testFindStaffAttendanceEntries() {
        Assert.assertNotNull("Data on demand for 'StaffAttendance' failed to initialize correctly", dod.getRandomStaffAttendance());
        long count = StaffAttendance.countStaffAttendances();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StaffAttendance> result = StaffAttendance.findStaffAttendanceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StaffAttendance' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StaffAttendance' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StaffAttendanceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StaffAttendance' failed to initialize correctly", dod.getRandomStaffAttendance());
        StaffAttendance obj = dod.getNewTransientStaffAttendance(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StaffAttendance' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StaffAttendance' identifier to be null", obj.getStaffAttendanceId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'StaffAttendance' identifier to no longer be null", obj.getStaffAttendanceId());
    }
    
    @Test
    public void StaffAttendanceIntegrationTest.testRemove() {
        StaffAttendance obj = dod.getRandomStaffAttendance();
        Assert.assertNotNull("Data on demand for 'StaffAttendance' failed to initialize correctly", obj);
        Integer id = obj.getStaffAttendanceId();
        Assert.assertNotNull("Data on demand for 'StaffAttendance' failed to provide an identifier", id);
        obj = StaffAttendance.findStaffAttendance(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StaffAttendance' with identifier '" + id + "'", StaffAttendance.findStaffAttendance(id));
    }
    
}
