// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.CountryDataOnDemand;
import com.school.base.domain.State;
import com.school.base.domain.StateDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect StateDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StateDataOnDemand: @Component;
    
    private Random StateDataOnDemand.rnd = new SecureRandom();
    
    private List<State> StateDataOnDemand.data;
    
    @Autowired
    CountryDataOnDemand StateDataOnDemand.countryDataOnDemand;
    
    public State StateDataOnDemand.getNewTransientState(int index) {
        State obj = new State();
        setState(obj, index);
        return obj;
    }
    
    public void StateDataOnDemand.setState(State obj, int index) {
        String state = "state_" + index;
        if (state.length() > 100) {
            state = state.substring(0, 100);
        }
        obj.setState(state);
    }
    
    public State StateDataOnDemand.getSpecificState(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        State obj = data.get(index);
        Integer id = obj.getStateId();
        return State.findState(id);
    }
    
    public State StateDataOnDemand.getRandomState() {
        init();
        State obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getStateId();
        return State.findState(id);
    }
    
    public boolean StateDataOnDemand.modifyState(State obj) {
        return false;
    }
    
    public void StateDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = State.findStateEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'State' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<State>();
        for (int i = 0; i < 10; i++) {
            State obj = getNewTransientState(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
