// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.State;
import com.school.base.domain.StateDataOnDemand;
import com.school.base.domain.StateIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StateIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StateIntegrationTest: @Transactional;
    
    @Autowired
    StateDataOnDemand StateIntegrationTest.dod;
    
    @Test
    public void StateIntegrationTest.testCountStates() {
        Assert.assertNotNull("Data on demand for 'State' failed to initialize correctly", dod.getRandomState());
        long count = State.countStates();
        Assert.assertTrue("Counter for 'State' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StateIntegrationTest.testFindState() {
        State obj = dod.getRandomState();
        Assert.assertNotNull("Data on demand for 'State' failed to initialize correctly", obj);
        Integer id = obj.getStateId();
        Assert.assertNotNull("Data on demand for 'State' failed to provide an identifier", id);
        obj = State.findState(id);
        Assert.assertNotNull("Find method for 'State' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'State' returned the incorrect identifier", id, obj.getStateId());
    }
    
    @Test
    public void StateIntegrationTest.testFindAllStates() {
        Assert.assertNotNull("Data on demand for 'State' failed to initialize correctly", dod.getRandomState());
        long count = State.countStates();
        Assert.assertTrue("Too expensive to perform a find all test for 'State', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<State> result = State.findAllStates();
        Assert.assertNotNull("Find all method for 'State' illegally returned null", result);
        Assert.assertTrue("Find all method for 'State' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StateIntegrationTest.testFindStateEntries() {
        Assert.assertNotNull("Data on demand for 'State' failed to initialize correctly", dod.getRandomState());
        long count = State.countStates();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<State> result = State.findStateEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'State' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'State' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StateIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'State' failed to initialize correctly", dod.getRandomState());
        State obj = dod.getNewTransientState(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'State' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'State' identifier to be null", obj.getStateId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'State' identifier to no longer be null", obj.getStateId());
    }
    
    @Test
    public void StateIntegrationTest.testRemove() {
        State obj = dod.getRandomState();
        Assert.assertNotNull("Data on demand for 'State' failed to initialize correctly", obj);
        Integer id = obj.getStateId();
        Assert.assertNotNull("Data on demand for 'State' failed to provide an identifier", id);
        obj = State.findState(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'State' with identifier '" + id + "'", State.findState(id));
    }
    
}
