// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.StudentExamination;
import com.school.base.domain.StudentExaminationDataOnDemand;
import com.school.base.domain.StudentExaminationIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StudentExaminationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StudentExaminationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StudentExaminationIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StudentExaminationIntegrationTest: @Transactional;
    
    @Autowired
    StudentExaminationDataOnDemand StudentExaminationIntegrationTest.dod;
    
    @Test
    public void StudentExaminationIntegrationTest.testCountStudentExaminations() {
        Assert.assertNotNull("Data on demand for 'StudentExamination' failed to initialize correctly", dod.getRandomStudentExamination());
        long count = StudentExamination.countStudentExaminations();
        Assert.assertTrue("Counter for 'StudentExamination' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StudentExaminationIntegrationTest.testFindStudentExamination() {
        StudentExamination obj = dod.getRandomStudentExamination();
        Assert.assertNotNull("Data on demand for 'StudentExamination' failed to initialize correctly", obj);
        Integer id = obj.getStudentExaminationId();
        Assert.assertNotNull("Data on demand for 'StudentExamination' failed to provide an identifier", id);
        obj = StudentExamination.findStudentExamination(id);
        Assert.assertNotNull("Find method for 'StudentExamination' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StudentExamination' returned the incorrect identifier", id, obj.getStudentExaminationId());
    }
    
    @Test
    public void StudentExaminationIntegrationTest.testFindAllStudentExaminations() {
        Assert.assertNotNull("Data on demand for 'StudentExamination' failed to initialize correctly", dod.getRandomStudentExamination());
        long count = StudentExamination.countStudentExaminations();
        Assert.assertTrue("Too expensive to perform a find all test for 'StudentExamination', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StudentExamination> result = StudentExamination.findAllStudentExaminations();
        Assert.assertNotNull("Find all method for 'StudentExamination' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StudentExamination' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StudentExaminationIntegrationTest.testFindStudentExaminationEntries() {
        Assert.assertNotNull("Data on demand for 'StudentExamination' failed to initialize correctly", dod.getRandomStudentExamination());
        long count = StudentExamination.countStudentExaminations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StudentExamination> result = StudentExamination.findStudentExaminationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StudentExamination' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StudentExamination' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StudentExaminationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StudentExamination' failed to initialize correctly", dod.getRandomStudentExamination());
        StudentExamination obj = dod.getNewTransientStudentExamination(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StudentExamination' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StudentExamination' identifier to be null", obj.getStudentExaminationId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'StudentExamination' identifier to no longer be null", obj.getStudentExaminationId());
    }
    
    @Test
    public void StudentExaminationIntegrationTest.testRemove() {
        StudentExamination obj = dod.getRandomStudentExamination();
        Assert.assertNotNull("Data on demand for 'StudentExamination' failed to initialize correctly", obj);
        Integer id = obj.getStudentExaminationId();
        Assert.assertNotNull("Data on demand for 'StudentExamination' failed to provide an identifier", id);
        obj = StudentExamination.findStudentExamination(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StudentExamination' with identifier '" + id + "'", StudentExamination.findStudentExamination(id));
    }
    
}
