// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.StudentAttedance;
import com.school.base.domain.StudentAttedanceDataOnDemand;
import com.school.base.domain.StudentAttedanceIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StudentAttedanceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StudentAttedanceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StudentAttedanceIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StudentAttedanceIntegrationTest: @Transactional;
    
    @Autowired
    StudentAttedanceDataOnDemand StudentAttedanceIntegrationTest.dod;
    
    @Test
    public void StudentAttedanceIntegrationTest.testCountStudentAttedances() {
        Assert.assertNotNull("Data on demand for 'StudentAttedance' failed to initialize correctly", dod.getRandomStudentAttedance());
        long count = StudentAttedance.countStudentAttedances();
        Assert.assertTrue("Counter for 'StudentAttedance' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StudentAttedanceIntegrationTest.testFindStudentAttedance() {
        StudentAttedance obj = dod.getRandomStudentAttedance();
        Assert.assertNotNull("Data on demand for 'StudentAttedance' failed to initialize correctly", obj);
        Long id = obj.getStudentAttendanceId();
        Assert.assertNotNull("Data on demand for 'StudentAttedance' failed to provide an identifier", id);
        obj = StudentAttedance.findStudentAttedance(id);
        Assert.assertNotNull("Find method for 'StudentAttedance' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StudentAttedance' returned the incorrect identifier", id, obj.getStudentAttendanceId());
    }
    
    @Test
    public void StudentAttedanceIntegrationTest.testFindAllStudentAttedances() {
        Assert.assertNotNull("Data on demand for 'StudentAttedance' failed to initialize correctly", dod.getRandomStudentAttedance());
        long count = StudentAttedance.countStudentAttedances();
        Assert.assertTrue("Too expensive to perform a find all test for 'StudentAttedance', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StudentAttedance> result = StudentAttedance.findAllStudentAttedances();
        Assert.assertNotNull("Find all method for 'StudentAttedance' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StudentAttedance' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StudentAttedanceIntegrationTest.testFindStudentAttedanceEntries() {
        Assert.assertNotNull("Data on demand for 'StudentAttedance' failed to initialize correctly", dod.getRandomStudentAttedance());
        long count = StudentAttedance.countStudentAttedances();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StudentAttedance> result = StudentAttedance.findStudentAttedanceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StudentAttedance' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StudentAttedance' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StudentAttedanceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StudentAttedance' failed to initialize correctly", dod.getRandomStudentAttedance());
        StudentAttedance obj = dod.getNewTransientStudentAttedance(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StudentAttedance' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StudentAttedance' identifier to be null", obj.getStudentAttendanceId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'StudentAttedance' identifier to no longer be null", obj.getStudentAttendanceId());
    }
    
    @Test
    public void StudentAttedanceIntegrationTest.testRemove() {
        StudentAttedance obj = dod.getRandomStudentAttedance();
        Assert.assertNotNull("Data on demand for 'StudentAttedance' failed to initialize correctly", obj);
        Long id = obj.getStudentAttendanceId();
        Assert.assertNotNull("Data on demand for 'StudentAttedance' failed to provide an identifier", id);
        obj = StudentAttedance.findStudentAttedance(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StudentAttedance' with identifier '" + id + "'", StudentAttedance.findStudentAttedance(id));
    }
    
}
