// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SchoolClassSection;
import com.school.base.domain.SchoolClassSectionDataOnDemand;
import com.school.base.domain.SchoolSubject;
import com.school.base.domain.SchoolSubjectDataOnDemand;
import com.school.base.domain.Staff;
import com.school.base.domain.StaffDataOnDemand;
import com.school.base.domain.SubjectStaffClass;
import com.school.base.domain.SubjectStaffClassDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SubjectStaffClassDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SubjectStaffClassDataOnDemand: @Component;
    
    private Random SubjectStaffClassDataOnDemand.rnd = new SecureRandom();
    
    private List<SubjectStaffClass> SubjectStaffClassDataOnDemand.data;
    
    @Autowired
    SchoolClassSectionDataOnDemand SubjectStaffClassDataOnDemand.schoolClassSectionDataOnDemand;
    
    @Autowired
    SchoolSubjectDataOnDemand SubjectStaffClassDataOnDemand.schoolSubjectDataOnDemand;
    
    @Autowired
    StaffDataOnDemand SubjectStaffClassDataOnDemand.staffDataOnDemand;
    
    public SubjectStaffClass SubjectStaffClassDataOnDemand.getNewTransientSubjectStaffClass(int index) {
        SubjectStaffClass obj = new SubjectStaffClass();
        setSchoolClassSectionId(obj, index);
        setSchoolSubjectId(obj, index);
        setStaffId(obj, index);
        return obj;
    }
    
    public void SubjectStaffClassDataOnDemand.setSchoolClassSectionId(SubjectStaffClass obj, int index) {
        SchoolClassSection schoolClassSectionId = schoolClassSectionDataOnDemand.getRandomSchoolClassSection();
        obj.setSchoolClassSectionId(schoolClassSectionId);
    }
    
    public void SubjectStaffClassDataOnDemand.setSchoolSubjectId(SubjectStaffClass obj, int index) {
        SchoolSubject schoolSubjectId = schoolSubjectDataOnDemand.getRandomSchoolSubject();
        obj.setSchoolSubjectId(schoolSubjectId);
    }
    
    public void SubjectStaffClassDataOnDemand.setStaffId(SubjectStaffClass obj, int index) {
        Staff staffId = staffDataOnDemand.getRandomStaff();
        obj.setStaffId(staffId);
    }
    
    public SubjectStaffClass SubjectStaffClassDataOnDemand.getSpecificSubjectStaffClass(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SubjectStaffClass obj = data.get(index);
        Integer id = obj.getSubjectStaffClassId();
        return SubjectStaffClass.findSubjectStaffClass(id);
    }
    
    public SubjectStaffClass SubjectStaffClassDataOnDemand.getRandomSubjectStaffClass() {
        init();
        SubjectStaffClass obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getSubjectStaffClassId();
        return SubjectStaffClass.findSubjectStaffClass(id);
    }
    
    public boolean SubjectStaffClassDataOnDemand.modifySubjectStaffClass(SubjectStaffClass obj) {
        return false;
    }
    
    public void SubjectStaffClassDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SubjectStaffClass.findSubjectStaffClassEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SubjectStaffClass' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SubjectStaffClass>();
        for (int i = 0; i < 10; i++) {
            SubjectStaffClass obj = getNewTransientSubjectStaffClass(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
