// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SchoolClass;
import com.school.base.domain.SchoolClassDataOnDemand;
import com.school.base.domain.SchoolSubject;
import com.school.base.domain.SchoolSubjectDataOnDemand;
import com.school.base.domain.SubjectClass;
import com.school.base.domain.SubjectClassDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SubjectClassDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SubjectClassDataOnDemand: @Component;
    
    private Random SubjectClassDataOnDemand.rnd = new SecureRandom();
    
    private List<SubjectClass> SubjectClassDataOnDemand.data;
    
    @Autowired
    SchoolClassDataOnDemand SubjectClassDataOnDemand.schoolClassDataOnDemand;
    
    @Autowired
    SchoolSubjectDataOnDemand SubjectClassDataOnDemand.schoolSubjectDataOnDemand;
    
    public SubjectClass SubjectClassDataOnDemand.getNewTransientSubjectClass(int index) {
        SubjectClass obj = new SubjectClass();
        setSchoolClassId(obj, index);
        setSchoolSubjectId(obj, index);
        return obj;
    }
    
    public void SubjectClassDataOnDemand.setSchoolClassId(SubjectClass obj, int index) {
        SchoolClass schoolClassId = schoolClassDataOnDemand.getRandomSchoolClass();
        obj.setSchoolClassId(schoolClassId);
    }
    
    public void SubjectClassDataOnDemand.setSchoolSubjectId(SubjectClass obj, int index) {
        SchoolSubject schoolSubjectId = schoolSubjectDataOnDemand.getRandomSchoolSubject();
        obj.setSchoolSubjectId(schoolSubjectId);
    }
    
    public SubjectClass SubjectClassDataOnDemand.getSpecificSubjectClass(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SubjectClass obj = data.get(index);
        Integer id = obj.getSubjectClassId();
        return SubjectClass.findSubjectClass(id);
    }
    
    public SubjectClass SubjectClassDataOnDemand.getRandomSubjectClass() {
        init();
        SubjectClass obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getSubjectClassId();
        return SubjectClass.findSubjectClass(id);
    }
    
    public boolean SubjectClassDataOnDemand.modifySubjectClass(SubjectClass obj) {
        return false;
    }
    
    public void SubjectClassDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SubjectClass.findSubjectClassEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SubjectClass' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SubjectClass>();
        for (int i = 0; i < 10; i++) {
            SubjectClass obj = getNewTransientSubjectClass(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
