// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.school.base.domain;

import com.school.base.domain.SubjectStaffClass;
import com.school.base.domain.SubjectStaffClassDataOnDemand;
import com.school.base.domain.SubjectStaffClassIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SubjectStaffClassIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SubjectStaffClassIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SubjectStaffClassIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SubjectStaffClassIntegrationTest: @Transactional;
    
    @Autowired
    SubjectStaffClassDataOnDemand SubjectStaffClassIntegrationTest.dod;
    
    @Test
    public void SubjectStaffClassIntegrationTest.testCountSubjectStaffClasses() {
        Assert.assertNotNull("Data on demand for 'SubjectStaffClass' failed to initialize correctly", dod.getRandomSubjectStaffClass());
        long count = SubjectStaffClass.countSubjectStaffClasses();
        Assert.assertTrue("Counter for 'SubjectStaffClass' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SubjectStaffClassIntegrationTest.testFindSubjectStaffClass() {
        SubjectStaffClass obj = dod.getRandomSubjectStaffClass();
        Assert.assertNotNull("Data on demand for 'SubjectStaffClass' failed to initialize correctly", obj);
        Integer id = obj.getSubjectStaffClassId();
        Assert.assertNotNull("Data on demand for 'SubjectStaffClass' failed to provide an identifier", id);
        obj = SubjectStaffClass.findSubjectStaffClass(id);
        Assert.assertNotNull("Find method for 'SubjectStaffClass' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SubjectStaffClass' returned the incorrect identifier", id, obj.getSubjectStaffClassId());
    }
    
    @Test
    public void SubjectStaffClassIntegrationTest.testFindAllSubjectStaffClasses() {
        Assert.assertNotNull("Data on demand for 'SubjectStaffClass' failed to initialize correctly", dod.getRandomSubjectStaffClass());
        long count = SubjectStaffClass.countSubjectStaffClasses();
        Assert.assertTrue("Too expensive to perform a find all test for 'SubjectStaffClass', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SubjectStaffClass> result = SubjectStaffClass.findAllSubjectStaffClasses();
        Assert.assertNotNull("Find all method for 'SubjectStaffClass' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SubjectStaffClass' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SubjectStaffClassIntegrationTest.testFindSubjectStaffClassEntries() {
        Assert.assertNotNull("Data on demand for 'SubjectStaffClass' failed to initialize correctly", dod.getRandomSubjectStaffClass());
        long count = SubjectStaffClass.countSubjectStaffClasses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SubjectStaffClass> result = SubjectStaffClass.findSubjectStaffClassEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SubjectStaffClass' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SubjectStaffClass' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SubjectStaffClassIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SubjectStaffClass' failed to initialize correctly", dod.getRandomSubjectStaffClass());
        SubjectStaffClass obj = dod.getNewTransientSubjectStaffClass(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SubjectStaffClass' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SubjectStaffClass' identifier to be null", obj.getSubjectStaffClassId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SubjectStaffClass' identifier to no longer be null", obj.getSubjectStaffClassId());
    }
    
    @Test
    public void SubjectStaffClassIntegrationTest.testRemove() {
        SubjectStaffClass obj = dod.getRandomSubjectStaffClass();
        Assert.assertNotNull("Data on demand for 'SubjectStaffClass' failed to initialize correctly", obj);
        Integer id = obj.getSubjectStaffClassId();
        Assert.assertNotNull("Data on demand for 'SubjectStaffClass' failed to provide an identifier", id);
        obj = SubjectStaffClass.findSubjectStaffClass(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SubjectStaffClass' with identifier '" + id + "'", SubjectStaffClass.findSubjectStaffClass(id));
    }
    
}
