package com.school.base.util;

public interface GeneralConstants {
	Integer STUDENT_STATUS_JUST_ADMITTED=10;
	Integer STUDENT_STATUS_ATTACHED_TO_A_CLASS=20;
	Integer STUDENT_STATUS_DETACHED_FROM_CLASS=30;
	Integer STUDENT_STATUS_PASSED_OUT=40;
	
	String PROMOTION_STATUS_PASSED_OUT="PASSED OUT";
	String PROMOTION_STATUS_PROMOTED="PROMOTED";
	String PROMOTION_STATUS_NOT_PROMOTED="NOT PROMOTED";

}
